# Conclusion

From our research, we have seen and proven that though treatment(in our dataset) might appear to have different effect on patients, by including confounder and other factors, we do not have enough evidence that the difference is solid. For the TNM diagnostics of breast cancer, we have seen that the general trend is: the larger the size of the tumor, the larger the number of lymph nodes tested positive, and the more abnormal looking cancer cell(higher cancer grade), the shorter a patient's survival might be, for both survival of death and recurrence. We have also seen that the most formidable aspect of breast cancer(or maybe all cancer) is the recurrence, as in our research there's not much time left if a patients tumor have recurred. But generally, breast cancer has a relative long survival and patients diagnosed with breast cancer should not be pessimistic but rather face reality and seek proper treatment. In this way, one might achieve as long survival as possible.

Of course, there are many limitations within our research and much more that we could explore in the realm of breast cancer. We will list a few for future study below. 

## Limitation

- As we have mentioned in Motivation, the TNM system for diagnosis of breast cancer relies on three important indicators, **Tumor**, **Node**, **Metastasis**. Now in our research, the dataset already contains information about tumor size, number of lymph nodes tested positive and somewhat incomplete metastasis, as we do not have information on patients with grade I cancer. This might lead to an overall pessimistic conclusion about survival times of breast cancer patients. For future studies, we think that it would be important to include grade I breast cancer incidence, as it is crucial to a more accurate estimate of patients' survival time.

- In Chapter 2, we compared the effect and the condition for choosing between chemotherapy and hormontherapy. We have had good results discerning the patients taking different therapy by age, as younger patients tend to take chemotherapy more and older patients tend to take hormontherapy more. And we have also seen that most patients with no lymph nodes tested positive choose neither of chemotherapy and hormontherapy. There might be other therapies that better suit mild condition patients. Additionally, nowadays, there are way more categories of therapies for breast cancer and many of them may have better effect on patients and less discerning characteristics like age with chemotherapy and hormontherapy. In future studies, these missing treatment shall be recorded, as it is critical to studying if the new methods are more effective and lasting treatment for breast cancer patients.

- In Chapter 3, we found out that in parametric models for recurrence vs. predictors, the coefficient for age is positive, which suggests that the older one patient is, the less likely he/she have recurred cancer. This counter-intuitive fact was explained by introducing the concept of competing risks. However, in the data that we obtained, there is no record of each patients' cause of death, and thus we could not conduct further analysis on what would be possible competing event that makes this relationship exist. In future study, if possible, researcher should try to record for patients with exact time of death their cause of death. In this manner, we might be able to study the causes of death for patients with breast cancer but did not die from the cancer itself.

## Reference

* “Breast Cancer - Stages.” Cancer.Net, 14 Aug. 2020, https://www.cancer.net/cancer-types/breast-cancer/stages.

* “Breast Cancer Grades” American Cancer Society, 20 Sep. 2019, https://www.cancer.org/cancer/breast-cancer/understanding-a-breast-cancer-diagnosis/breast-cancer-grades.html.

* “Breast Cancer Statistics.” Centers for Disease Control and Prevention, Centers for Disease Control and Prevention, 8 June 2020, www.cdc.gov/cancer/breast/statistics/index.htm.

* “Breast Cancer Survival Statistics.” Cancer Research UK, 22 Jan. 2021, www.cancerresearchuk.org/health-professional/cancer-statistics/statistics-by-cancer-type/breast-cancer/survival#heading-Zero.

* “Cancer.” World Health Organization, World Health Organization, www.who.int/news-room/fact-sheets/detail/cancer.

* Martin, Laura J. “Breast Cancer: What Are the Survival Rates?” WebMD, WebMD, 13 May 2020, www.webmd.com/breast-cancer/guide/breast-cancer-survival-rates#:~:text=The 10-year breast cancer,are alive after 10 years).