<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta property="og:title" content="3.4 Parametric Models | Rotterdam" />
<meta property="og:type" content="book" />





<meta name="author" content="JACK TAN, YIMING MIAO" />

<meta name="date" content="2021-03-14" />

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS_CHTML-full" type="text/javascript"></script>

<meta name="description" content="3.4 Parametric Models | Rotterdam">

<title>3.4 Parametric Models | Rotterdam</title>

<script src="libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="libs/navigation-1.1/tabsets.js"></script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<link rel="stylesheet" href="toc.css" type="text/css" />

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
</style>
</head>

<body>

<div class="container-fluid main-container">


<div class="row">
<div class="col-sm-12">
<div id="TOC">
<ul>
<li class="has-sub"><a href="index.html#motivation"><span class="toc-section-number">1</span> Motivation</a><ul>
<li><a href="1-1-some-background-information.html#some-background-information"><span class="toc-section-number">1.1</span> Some Background Information</a></li>
</ul></li>
<li class="has-sub"><a href="2-data-exploration.html#data-exploration"><span class="toc-section-number">2</span> Data Exploration</a><ul>
<li><a href="2-1-loading-data.html#loading-data"><span class="toc-section-number">2.1</span> Loading Data</a></li>
<li class="has-sub"><a href="2-2-data-wrangling.html#data-wrangling"><span class="toc-section-number">2.2</span> Data Wrangling</a><ul>
<li><a href="2-2-data-wrangling.html#ttumornnodemmetastasis"><span class="toc-section-number">2.2.1</span> T(Tumor)N(Node)M(Metastasis)</a></li>
<li><a href="2-2-data-wrangling.html#treatment"><span class="toc-section-number">2.2.2</span> Treatment</a></li>
</ul></li>
<li class="has-sub"><a href="2-3-data-visualizations-and-exploration.html#data-visualizations-and-exploration"><span class="toc-section-number">2.3</span> Data visualizations and exploration</a><ul>
<li><a href="2-3-data-visualizations-and-exploration.html#diagnostics-vs.-survival-times"><span class="toc-section-number">2.3.1</span> Diagnostics vs. Survival Times</a></li>
<li><a href="2-3-data-visualizations-and-exploration.html#treatment-vs.-survival-times"><span class="toc-section-number">2.3.2</span> Treatment vs. Survival Times</a></li>
<li><a href="2-3-data-visualizations-and-exploration.html#age-treatment-vs.-survival-times"><span class="toc-section-number">2.3.3</span> <code>age</code> + <code>Treatment</code> vs. Survival Times</a></li>
<li><a href="2-3-data-visualizations-and-exploration.html#treatment-vs.-tnm"><span class="toc-section-number">2.3.4</span> <code>Treatment</code> vs. TNM</a></li>
<li><a href="2-3-data-visualizations-and-exploration.html#general-x-year-survival-rate"><span class="toc-section-number">2.3.5</span> General X-year Survival Rate</a></li>
</ul></li>
</ul></li>
<li class="has-sub"><a href="3-survival-analysis.html#survival-analysis"><span class="toc-section-number">3</span> Survival Analysis</a><ul>
<li><a href="3-1-notation.html#notation"><span class="toc-section-number">3.1</span> Notation</a></li>
<li><a href="3-2-kaplan-miere-estimator-of-the-entire-dataset.html#kaplan-miere-estimator-of-the-entire-dataset"><span class="toc-section-number">3.2</span> Kaplan-Miere estimator of the entire dataset</a></li>
<li class="has-sub"><a href="3-3-kaplan-miere-estimator-on-different-variables-in-rotterdam.html#kaplan-miere-estimator-on-different-variables-in-rotterdam"><span class="toc-section-number">3.3</span> Kaplan-Miere estimator on different variables in <code>rotterdam</code></a><ul>
<li><a href="3-3-kaplan-miere-estimator-on-different-variables-in-rotterdam.html#size-vs.-survival-times"><span class="toc-section-number">3.3.1</span> <code>size</code> vs. Survival Times</a></li>
<li><a href="3-3-kaplan-miere-estimator-on-different-variables-in-rotterdam.html#nodes_level-vs.-survival-times"><span class="toc-section-number">3.3.2</span> <code>Nodes_level</code> vs. Survival Times</a></li>
<li><a href="3-3-kaplan-miere-estimator-on-different-variables-in-rotterdam.html#grade-vs.-survival-times"><span class="toc-section-number">3.3.3</span> <code>grade</code> vs. Survival Times</a></li>
<li><a href="3-3-kaplan-miere-estimator-on-different-variables-in-rotterdam.html#treatment-vs.-survival-times-1"><span class="toc-section-number">3.3.4</span> <code>Treatment</code> vs. Survival Times</a></li>
</ul></li>
<li class="has-sub"><a href="3-4-parametric-models.html#parametric-models"><span class="toc-section-number">3.4</span> Parametric Models</a><ul>
<li><a href="3-4-parametric-models.html#user-defined-cox-snell-function"><span class="toc-section-number">3.4.1</span> User-defined Cox-Snell function</a></li>
<li><a href="3-4-parametric-models.html#exponential-and-weibull"><span class="toc-section-number">3.4.2</span> Exponential and Weibull</a></li>
<li><a href="3-4-parametric-models.html#log-normal-models"><span class="toc-section-number">3.4.3</span> Log-normal models</a></li>
</ul></li>
<li class="has-sub"><a href="3-5-cox-ph-model.html#cox-ph-model"><span class="toc-section-number">3.5</span> Cox-PH model:</a><ul>
<li><a href="3-5-cox-ph-model.html#cox-ph-model-for-dtime"><span class="toc-section-number">3.5.1</span> Cox-PH model for <code>dtime</code></a></li>
<li><a href="3-5-cox-ph-model.html#cox-ph-model-for-rtime"><span class="toc-section-number">3.5.2</span> Cox-PH model for <code>rtime</code></a></li>
</ul></li>
<li><a href="3-6-summary.html#summary"><span class="toc-section-number">3.6</span> Summary</a></li>
</ul></li>
<li class="has-sub"><a href="4-random-survival-forest.html#random-survival-forest"><span class="toc-section-number">4</span> Random Survival Forest</a><ul>
<li><a href="4-1-dtime.html#dtime"><span class="toc-section-number">4.1</span> <code>dtime</code></a></li>
<li><a href="4-2-rtime.html#rtime"><span class="toc-section-number">4.2</span> <code>rtime</code></a></li>
</ul></li>
<li class="has-sub"><a href="5-conclusion.html#conclusion"><span class="toc-section-number">5</span> Conclusion</a><ul>
<li><a href="5-1-limitation.html#limitation"><span class="toc-section-number">5.1</span> Limitation</a></li>
<li><a href="5-2-reference.html#reference"><span class="toc-section-number">5.2</span> Reference</a></li>
</ul></li>
</ul>
</div>
</div>
</div>
<div class="row">
<div class="col-sm-12">
<div id="parametric-models" class="section level2">
<h2><span class="header-section-number">3.4</span> Parametric Models</h2>
<p>Another point that we are going to explore is if we would be able to fit our data to a parametric model. This matters since if we could fit any parametric model, then we should have a model good enough to generate predictions of breast cancer patients’ survival and would have nice and interpretable coefficients to work with.</p>
<p>To do so, we will begin by checking if any of Exponential, Weibull, or Log-normal distribution would be adequate parametric assumption to cast on our data. We will verify the adequacy by checking the Cox-Snell residual plot. We will be fitting models using variables: <code>Treatment</code>, <code>size</code>, <code>nodes</code>, <code>grade</code>, <code>age</code> (we have shown in Chapter 2 that age is a confounder for categories in Treatment).</p>
<div id="user-defined-cox-snell-function" class="section level3">
<h3><span class="header-section-number">3.4.1</span> User-defined Cox-Snell function</h3>
<p>If we fit Exponential model on the survival time, we have the function <span class="math inline">\(S(t) = e^{-\lambda t}\)</span>, and we can transform the survival function into an expression for the “complementary log-log”:</p>
<p><span class="math display">\[\begin{align*}
S(t) &amp;= e^{-\lambda t} \\
\log[S(t)] &amp;= -\lambda t \\
-\log[S(t)] &amp;= \lambda t \\
\log\big(-\log[S(t)] \big) &amp;= \log\lambda + \log t
\end{align*}\]</span></p>
<p>Then, if we let <span class="math inline">\(y=\log\big(-\log[S(t)] \big)\)</span>, <span class="math inline">\(m=1\)</span>, <span class="math inline">\(b=\log(\lambda)\)</span>, and <span class="math inline">\(x=\log(t)\)</span>, then we can view the equation in the form <span class="math inline">\(y=mx+b = 1*x+b\)</span>.</p>
<p>This means that if Exponential model is adequate, its complementary log-log plot should be a linear line with slope=1 and intercept=0.</p>
<p>And for any other parametric model, we can define a Cox-Snell residual as <span class="math inline">\(CS_i = -log(\hat{S}_p(t_i|x_i))\)</span> for <span class="math inline">\(i=1,\dots, n\)</span>, and <span class="math inline">\(CS_i\)</span>s should behave like data drawn from an Exponential distribution (<span class="math inline">\(\lambda=1\)</span>).</p>
<p>Thus, we can check the adequacy of any model by checking the Exponential-ness of its Cox-Snell residuals. We can graph <span class="math inline">\(CS_i\)</span> vs <span class="math inline">\(log(CS_i)\)</span>, and the graph should also look linear with slope =1 and intercept=0, if the parametric model is adequate for the data.</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb77-1" title="1"><span class="co"># The Cox-Snell function takes as inputs</span></a>
<a class="sourceLine" id="cb77-2" title="2"><span class="co"># 1. A vector of Cox-Snell residuals created by the user based on the model being evaluated,</span></a>
<a class="sourceLine" id="cb77-3" title="3"><span class="co"># 2. A status vector</span></a>
<a class="sourceLine" id="cb77-4" title="4"><span class="co"># 3. Optional x- and y- limits for the resulting plot</span></a>
<a class="sourceLine" id="cb77-5" title="5"></a>
<a class="sourceLine" id="cb77-6" title="6">CoxSnell =<span class="st"> </span><span class="cf">function</span>(cs,status,<span class="dt">xlim=</span><span class="ot">NULL</span>,<span class="dt">ylim=</span><span class="ot">NULL</span>)</a>
<a class="sourceLine" id="cb77-7" title="7">{</a>
<a class="sourceLine" id="cb77-8" title="8">kmcs =<span class="st"> </span><span class="kw">survfit</span>(<span class="kw">Surv</span>(<span class="kw">jitter</span>(cs,<span class="dt">amount=</span>(<span class="kw">max</span>(cs)<span class="op">-</span><span class="kw">min</span>(cs))<span class="op">/</span><span class="dv">1000</span>),status) <span class="op">~</span><span class="st"> </span><span class="dv">1</span>)<span class="op">$</span>surv</a>
<a class="sourceLine" id="cb77-9" title="9"></a>
<a class="sourceLine" id="cb77-10" title="10"><span class="kw">plot</span>(<span class="kw">log</span>(<span class="op">-</span><span class="kw">log</span>(kmcs)) <span class="op">~</span><span class="st"> </span><span class="kw">sort</span>(<span class="kw">log</span>(cs)) ,</a>
<a class="sourceLine" id="cb77-11" title="11">      <span class="dt">xlab=</span><span class="st">&quot;log(Cox-Snell)&quot;</span>, <span class="dt">ylab=</span><span class="st">&quot;log(-log(S(Cox-Snell)))&quot;</span>, <span class="dt">xlim=</span>xlim, <span class="dt">ylim=</span>ylim )</a>
<a class="sourceLine" id="cb77-12" title="12"></a>
<a class="sourceLine" id="cb77-13" title="13"><span class="kw">abline</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dt">col=</span><span class="st">&#39;red&#39;</span>)</a>
<a class="sourceLine" id="cb77-14" title="14">}</a></code></pre></div>
</div>
<div id="exponential-and-weibull" class="section level3">
<h3><span class="header-section-number">3.4.2</span> Exponential and Weibull</h3>
<p>We first tried to examine the adquacy of Exponential and Weibull model, but none of them are adquate for our dataset:</p>
<ol style="list-style-type: decimal">
<li><code>dtime, death ~ Treatment + size + nodes + grade + age</code> under Exponential:</li>
</ol>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb78-1" title="1">Dexp &lt;-<span class="st"> </span><span class="kw">survreg</span>(<span class="kw">Surv</span>(dtime, death) <span class="op">~</span><span class="st"> </span>Treatment <span class="op">+</span><span class="st"> </span>size <span class="op">+</span><span class="st"> </span>nodes <span class="op">+</span><span class="st"> </span>grade <span class="op">+</span><span class="st"> </span>age, <span class="dt">dist=</span><span class="st">&#39;exponential&#39;</span>, <span class="dt">data=</span>rotterdam)</a>
<a class="sourceLine" id="cb78-2" title="2">Dexp</a></code></pre></div>
<pre><code>## Call:
## survreg(formula = Surv(dtime, death) ~ Treatment + size + nodes + 
##     grade + age, data = rotterdam, dist = &quot;exponential&quot;)
## 
## Coefficients:
##                  (Intercept)               TreatmentChemo 
##                  10.72043480                  -0.51333347 
##              TreatmentHormon TreatmentNaN/Other Treatment 
##                  -0.41382108                  -0.45674929 
##                    size20-50                      size&gt;50 
##                  -0.44229181                  -0.76874022 
##                        nodes                       grade3 
##                  -0.06922296                  -0.32925464 
##                          age 
##                  -0.01424763 
## 
## Scale fixed at 1 
## 
## Loglik(model)= -12125.2   Loglik(intercept only)= -12360.4
##  Chisq= 470.37 on 8 degrees of freedom, p= &lt;2e-16 
## n= 2982</code></pre>
<p><img src="Cox-Snell/DWeibull.png" /></p>
<ol start="2" style="list-style-type: decimal">
<li><code>rtime, recur ~ Treatment + size + nodes + grade + age</code> under Exponential:</li>
</ol>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb80-1" title="1">Rexp &lt;-<span class="st"> </span><span class="kw">survreg</span>(<span class="kw">Surv</span>(rtime, recur) <span class="op">~</span><span class="st"> </span>Treatment <span class="op">+</span><span class="st"> </span>size <span class="op">+</span><span class="st"> </span>nodes <span class="op">+</span><span class="st"> </span>grade <span class="op">+</span><span class="st"> </span>age, <span class="dt">dist=</span><span class="st">&#39;exponential&#39;</span>, <span class="dt">data=</span>rotterdam)</a>
<a class="sourceLine" id="cb80-2" title="2">Rexp</a></code></pre></div>
<pre><code>## Call:
## survreg(formula = Surv(rtime, recur) ~ Treatment + size + nodes + 
##     grade + age, data = rotterdam, dist = &quot;exponential&quot;)
## 
## Coefficients:
##                  (Intercept)               TreatmentChemo 
##                  9.081159515                 -0.373811470 
##              TreatmentHormon TreatmentNaN/Other Treatment 
##                 -0.507332960                 -0.485387357 
##                    size20-50                      size&gt;50 
##                 -0.372059978                 -0.654240460 
##                        nodes                       grade3 
##                 -0.080821343                 -0.393920415 
##                          age 
##                  0.008095379 
## 
## Scale fixed at 1 
## 
## Loglik(model)= -13897.4   Loglik(intercept only)= -14153.7
##  Chisq= 512.6 on 8 degrees of freedom, p= &lt;2e-16 
## n= 2982</code></pre>
<p><img src="Cox-Snell/Rexp.png" /></p>
<ol start="3" style="list-style-type: decimal">
<li><code>dtime, death ~ Treatment + size + nodes + grade + age</code> under Weibull:</li>
</ol>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb82-1" title="1">Dweibull &lt;-<span class="st"> </span><span class="kw">survreg</span>(<span class="kw">Surv</span>(dtime, death) <span class="op">~</span><span class="st"> </span>Treatment <span class="op">+</span><span class="st"> </span>size <span class="op">+</span><span class="st"> </span>nodes <span class="op">+</span><span class="st"> </span>grade <span class="op">+</span><span class="st"> </span>age, <span class="dt">dist=</span><span class="st">&#39;weibull&#39;</span>, <span class="dt">data=</span>rotterdam)</a>
<a class="sourceLine" id="cb82-2" title="2">Dweibull</a></code></pre></div>
<pre><code>## Call:
## survreg(formula = Surv(dtime, death) ~ Treatment + size + nodes + 
##     grade + age, data = rotterdam, dist = &quot;weibull&quot;)
## 
## Coefficients:
##                  (Intercept)               TreatmentChemo 
##                  10.10735484                  -0.39504003 
##              TreatmentHormon TreatmentNaN/Other Treatment 
##                  -0.37941684                  -0.35423500 
##                    size20-50                      size&gt;50 
##                  -0.33487166                  -0.61672126 
##                        nodes                       grade3 
##                  -0.05500626                  -0.26093659 
##                          age 
##                  -0.01130402 
## 
## Scale= 0.7370449 
## 
## Loglik(model)= -12055.3   Loglik(intercept only)= -12322.7
##  Chisq= 534.68 on 8 degrees of freedom, p= &lt;2e-16 
## n= 2982</code></pre>
<p><img src="Cox-Snell/DWeibull.png" /></p>
<ol start="4" style="list-style-type: decimal">
<li><code>rtime, recur ~ Treatment + size + nodes + grade + age</code> under Weibull:</li>
</ol>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb84-1" title="1">Rweibull &lt;-<span class="st"> </span><span class="kw">survreg</span>(<span class="kw">Surv</span>(rtime, recur) <span class="op">~</span><span class="st"> </span>Treatment <span class="op">+</span><span class="st"> </span>size <span class="op">+</span><span class="st"> </span>nodes <span class="op">+</span><span class="st"> </span>grade <span class="op">+</span><span class="st"> </span>age, <span class="dt">dist=</span><span class="st">&#39;weibull&#39;</span>, <span class="dt">data=</span>rotterdam)</a>
<a class="sourceLine" id="cb84-2" title="2">Rweibull</a></code></pre></div>
<pre><code>## Call:
## survreg(formula = Surv(rtime, recur) ~ Treatment + size + nodes + 
##     grade + age, data = rotterdam, dist = &quot;weibull&quot;)
## 
## Coefficients:
##                  (Intercept)               TreatmentChemo 
##                  9.092880859                 -0.376425745 
##              TreatmentHormon TreatmentNaN/Other Treatment 
##                 -0.508855839                 -0.489527042 
##                    size20-50                      size&gt;50 
##                 -0.376473401                 -0.659532060 
##                        nodes                       grade3 
##                 -0.081625087                 -0.398251643 
##                          age 
##                  0.008216064 
## 
## Scale= 1.014145 
## 
## Loglik(model)= -13897.2   Loglik(intercept only)= -14145.7
##  Chisq= 497.1 on 8 degrees of freedom, p= &lt;2e-16 
## n= 2982</code></pre>
<p><img src="Cox-Snell/RWeibull.png" /></p>
</div>
<div id="log-normal-models" class="section level3">
<h3><span class="header-section-number">3.4.3</span> Log-normal models</h3>
<p>Finally, we will examine the adequacy of Log-normal model.</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb86-1" title="1">Dlnorm &lt;-<span class="st"> </span><span class="kw">survreg</span>(<span class="kw">Surv</span>(dtime, death) <span class="op">~</span><span class="st"> </span>Treatment <span class="op">+</span><span class="st"> </span>size <span class="op">+</span><span class="st"> </span>nodes <span class="op">+</span><span class="st"> </span>grade <span class="op">+</span><span class="st"> </span>age , <span class="dt">dist=</span><span class="st">&#39;lognormal&#39;</span>, <span class="dt">data=</span>rotterdam)</a>
<a class="sourceLine" id="cb86-2" title="2"><span class="kw">summary</span>(Dlnorm)</a></code></pre></div>
<pre><code>## 
## Call:
## survreg(formula = Surv(dtime, death) ~ Treatment + size + nodes + 
##     grade + age, data = rotterdam, dist = &quot;lognormal&quot;)
##                                 Value Std. Error      z       p
## (Intercept)                   9.91513    0.27975  35.44 &lt; 2e-16
## TreatmentChemo               -0.42503    0.26292  -1.62   0.106
## TreatmentHormon              -0.31448    0.26896  -1.17   0.242
## TreatmentNaN/Other Treatment -0.41617    0.26011  -1.60   0.110
## size20-50                    -0.34787    0.05108  -6.81 9.8e-12
## size&gt;50                      -0.60916    0.08067  -7.55 4.3e-14
## nodes                        -0.07773    0.00544 -14.29 &lt; 2e-16
## grade3                       -0.30866    0.05490  -5.62 1.9e-08
## age                          -0.01005    0.00197  -5.10 3.3e-07
## Log(scale)                    0.06670    0.02162   3.08   0.002
## 
## Scale= 1.07 
## 
## Log Normal distribution
## Loglik(model)= -12018.2   Loglik(intercept only)= -12286.5
##  Chisq= 536.66 on 8 degrees of freedom, p= 9.5e-111 
## Number of Newton-Raphson Iterations: 4 
## n= 2982</code></pre>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb88-1" title="1">CS_LnormD &lt;-<span class="st"> </span><span class="op">-</span><span class="kw">log</span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="kw">plnorm</span>(rotterdam<span class="op">$</span>dtime, <span class="fl">9.91512622-0.42502769</span><span class="op">*</span>(rotterdam<span class="op">$</span>Treatment<span class="op">==</span><span class="st">&quot;Chemo&quot;</span>)</a>
<a class="sourceLine" id="cb88-2" title="2">                                                  <span class="fl">-0.31448004</span><span class="op">*</span>(rotterdam<span class="op">$</span>Treatment<span class="op">==</span><span class="st">&quot;Hormon&quot;</span>)  </a>
<a class="sourceLine" id="cb88-3" title="3">                                                  <span class="fl">-0.41616843</span><span class="op">*</span>(rotterdam<span class="op">$</span>Treatment<span class="op">==</span><span class="st">&quot;NaN/Other Treatment&quot;</span>)</a>
<a class="sourceLine" id="cb88-4" title="4">                                                  <span class="fl">-0.34787441</span><span class="op">*</span>(rotterdam<span class="op">$</span>size<span class="op">==</span><span class="st">&quot;20-50&quot;</span>)</a>
<a class="sourceLine" id="cb88-5" title="5">                                                  <span class="fl">-0.60916461</span><span class="op">*</span>(rotterdam<span class="op">$</span>size<span class="op">==</span><span class="st">&quot;&gt;50&quot;</span>)</a>
<a class="sourceLine" id="cb88-6" title="6">                                                  <span class="fl">-0.07772719</span><span class="op">*</span>rotterdam<span class="op">$</span>nodes</a>
<a class="sourceLine" id="cb88-7" title="7">                                                  <span class="fl">-0.30866307</span><span class="op">*</span>(rotterdam<span class="op">$</span>grade<span class="op">==</span><span class="st">&quot;3&quot;</span>)</a>
<a class="sourceLine" id="cb88-8" title="8">                                                  <span class="fl">-0.01004650</span><span class="op">*</span>rotterdam<span class="op">$</span>age, </a>
<a class="sourceLine" id="cb88-9" title="9">                                       <span class="fl">1.06897</span>))</a>
<a class="sourceLine" id="cb88-10" title="10"><span class="co"># Make appropriate graph using CoxSnell function</span></a>
<a class="sourceLine" id="cb88-11" title="11"><span class="kw">CoxSnell</span>(CS_LnormD, rotterdam<span class="op">$</span>death)</a></code></pre></div>
<p><img src="Rotterdam_files/figure-html/unnamed-chunk-67-1.png" width="672" /></p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb89-1" title="1">Rlnorm &lt;-<span class="st"> </span><span class="kw">survreg</span>(<span class="kw">Surv</span>(rtime, recur) <span class="op">~</span><span class="st"> </span>Treatment <span class="op">+</span><span class="st"> </span>size <span class="op">+</span><span class="st"> </span>nodes <span class="op">+</span><span class="st"> </span>grade <span class="op">+</span><span class="st"> </span>age, <span class="dt">dist=</span><span class="st">&#39;lognormal&#39;</span>, <span class="dt">data=</span>rotterdam)</a>
<a class="sourceLine" id="cb89-2" title="2"><span class="kw">summary</span>(Rlnorm)</a></code></pre></div>
<pre><code>## 
## Call:
## survreg(formula = Surv(rtime, recur) ~ Treatment + size + nodes + 
##     grade + age, data = rotterdam, dist = &quot;lognormal&quot;)
##                                 Value Std. Error      z       p
## (Intercept)                   8.78912    0.30877  28.46 &lt; 2e-16
## TreatmentChemo               -0.36139    0.29098  -1.24 0.21425
## TreatmentHormon              -0.41809    0.29943  -1.40 0.16263
## TreatmentNaN/Other Treatment -0.58078    0.28741  -2.02 0.04331
## size20-50                    -0.41866    0.05992  -6.99 2.8e-12
## size&gt;50                      -0.67179    0.09845  -6.82 8.9e-12
## nodes                        -0.10590    0.00662 -16.00 &lt; 2e-16
## grade3                       -0.43987    0.06470  -6.80 1.1e-11
## age                           0.00892    0.00238   3.75 0.00018
## Log(scale)                    0.28360    0.01980  14.33 &lt; 2e-16
## 
## Scale= 1.33 
## 
## Log Normal distribution
## Loglik(model)= -13780.4   Loglik(intercept only)= -14045.8
##  Chisq= 530.65 on 8 degrees of freedom, p= 1.9e-109 
## Number of Newton-Raphson Iterations: 4 
## n= 2982</code></pre>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb91-1" title="1">CS_LnormR &lt;-<span class="st"> </span><span class="op">-</span><span class="kw">log</span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="kw">plnorm</span>(rotterdam<span class="op">$</span>rtime, <span class="fl">8.78912009-0.36138607</span><span class="op">*</span>(rotterdam<span class="op">$</span>Treatment<span class="op">==</span><span class="st">&quot;Chemo&quot;</span>)</a>
<a class="sourceLine" id="cb91-2" title="2">                                                  <span class="fl">-0.41809135</span><span class="op">*</span>(rotterdam<span class="op">$</span>Treatment<span class="op">==</span><span class="st">&quot;Hormon&quot;</span>)   </a>
<a class="sourceLine" id="cb91-3" title="3">                                                  <span class="fl">-0.58077716</span><span class="op">*</span>(rotterdam<span class="op">$</span>Treatment<span class="op">==</span><span class="st">&quot;NaN/Other Treatment&quot;</span>)</a>
<a class="sourceLine" id="cb91-4" title="4">                                                  <span class="fl">-0.41865655</span><span class="op">*</span>(rotterdam<span class="op">$</span>size<span class="op">==</span><span class="st">&quot;20-50&quot;</span>)</a>
<a class="sourceLine" id="cb91-5" title="5">                                                  <span class="fl">-0.67178824</span><span class="op">*</span>(rotterdam<span class="op">$</span>size<span class="op">==</span><span class="st">&quot;&gt;50&quot;</span>)</a>
<a class="sourceLine" id="cb91-6" title="6">                                                  <span class="fl">-0.10590430</span><span class="op">*</span>rotterdam<span class="op">$</span>nodes </a>
<a class="sourceLine" id="cb91-7" title="7">                                                  <span class="fl">-0.43987388</span><span class="op">*</span>(rotterdam<span class="op">$</span>grade<span class="op">==</span><span class="st">&quot;3&quot;</span>)</a>
<a class="sourceLine" id="cb91-8" title="8">                                                  <span class="fl">+0.00892277</span><span class="op">*</span>rotterdam<span class="op">$</span>age, </a>
<a class="sourceLine" id="cb91-9" title="9">                                      <span class="fl">1.327904</span>))</a>
<a class="sourceLine" id="cb91-10" title="10"></a>
<a class="sourceLine" id="cb91-11" title="11"><span class="co"># Make appropriate graph using CoxSnell function</span></a>
<a class="sourceLine" id="cb91-12" title="12"><span class="kw">CoxSnell</span>(CS_LnormR, rotterdam<span class="op">$</span>recur)</a></code></pre></div>
<p><img src="Rotterdam_files/figure-html/unnamed-chunk-68-1.png" width="672" /></p>
<p>We could see that the Log-normal parametric model is an adequate model for both the <code>dtime</code> and <code>rtime</code> vs. <code>Treatment</code> + <code>size</code> + <code>nodes</code> + <code>grade</code> + <code>age</code>.</p>
<div id="interpretation-of-the-coefficients" class="section level4">
<h4><span class="header-section-number">3.4.3.1</span> Interpretation of the coefficients</h4>
<p>Lognormal is an example of a class of models called Accelerated Failure Time (AFT) models, in which every 1-unit increase in <span class="math inline">\(x_i\)</span> is associated with a scaling of time by <span class="math inline">\(e^{c_i}\)</span>, where <span class="math inline">\(c\)</span> is the coefficient of <span class="math inline">\(x\)</span> in the regression model. The quantity <span class="math inline">\(e^{c_i}\)</span>
is referred to as a time ratio (TR), and thus each <span class="math inline">\(c_i\)</span> represents a log(TR).</p>
<p>Thus, the results of our lognormal model can be interpreted in the following way:</p>
<div id="for-dtime" class="section level5">
<h5><span class="header-section-number">3.4.3.1.1</span> For <code>dtime</code>:</h5>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb92-1" title="1"><span class="kw">exp</span>(<span class="op">-</span><span class="fl">0.42502769</span>) <span class="co"># chemo</span></a></code></pre></div>
<pre><code>## [1] 0.6537517</code></pre>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb94-1" title="1"><span class="kw">exp</span>(<span class="op">-</span><span class="fl">0.3144800</span>) <span class="co"># hormon</span></a></code></pre></div>
<pre><code>## [1] 0.7301685</code></pre>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb96-1" title="1"><span class="kw">exp</span>(<span class="op">-</span><span class="fl">0.41616843</span>) <span class="co"># NaN/Other Treatment</span></a></code></pre></div>
<pre><code>## [1] 0.6595692</code></pre>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb98-1" title="1"><span class="kw">exp</span>(<span class="op">-</span><span class="fl">0.34787441</span>) <span class="co"># size 20-50</span></a></code></pre></div>
<pre><code>## [1] 0.7061876</code></pre>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb100-1" title="1"><span class="kw">exp</span>(<span class="op">-</span><span class="fl">0.60916461</span>) <span class="co"># size &gt;50</span></a></code></pre></div>
<pre><code>## [1] 0.543805</code></pre>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb102-1" title="1"><span class="kw">exp</span>(<span class="op">-</span><span class="fl">0.07772719</span>) <span class="co"># nodes</span></a></code></pre></div>
<pre><code>## [1] 0.9252168</code></pre>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb104-1" title="1"><span class="kw">exp</span>(<span class="op">-</span><span class="fl">0.30866307</span>) <span class="co"># grade 3</span></a></code></pre></div>
<pre><code>## [1] 0.7344282</code></pre>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb106-1" title="1"><span class="kw">exp</span>(<span class="op">-</span><span class="fl">0.01004650</span>) <span class="co"># age</span></a></code></pre></div>
<pre><code>## [1] 0.9900038</code></pre>
<p>Having chemotherapy, hormon-therapy and NaN/Other Treatment is associated with a scaling of mean survival time by 0.6537517, 0.7301685 and 0.6595692 respectively, compared to having both chemo and hormon therapies. However, the relationships are all insignificant.</p>
<p>Compared to tumor size &lt;=20mm, having tumor size 20-50mm and &gt;50mm will make the expected survival time scaled by 0.7061876 and 0.543805.</p>
<p>For node and age, each extra positive lymph nodes and every 1-year increase in age is associated with a scaling of mean survival time by 0.9252168 and 0.9900038.</p>
<p>And compared to grade II, grade III of cancer cell makes the expected survival time multiplied by 0.7344282.</p>
</div>
<div id="for-rtime" class="section level5">
<h5><span class="header-section-number">3.4.3.1.2</span> For <code>rtime</code>:</h5>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb108-1" title="1"><span class="kw">exp</span>(<span class="op">-</span><span class="fl">0.36138607</span>) <span class="co"># chemo</span></a></code></pre></div>
<pre><code>## [1] 0.69671</code></pre>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb110-1" title="1"><span class="kw">exp</span>(<span class="op">-</span><span class="fl">0.41809135</span>) <span class="co"># hormon</span></a></code></pre></div>
<pre><code>## [1] 0.6583021</code></pre>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb112-1" title="1"><span class="kw">exp</span>(<span class="op">-</span><span class="fl">0.58077716</span>) <span class="co"># NaN/Other Treatment</span></a></code></pre></div>
<pre><code>## [1] 0.5594634</code></pre>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb114-1" title="1"><span class="kw">exp</span>(<span class="op">-</span><span class="fl">0.41865655</span>) <span class="co"># size 20-50</span></a></code></pre></div>
<pre><code>## [1] 0.6579301</code></pre>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb116-1" title="1"><span class="kw">exp</span>(<span class="op">-</span><span class="fl">0.67178824</span>) <span class="co"># size &gt;50</span></a></code></pre></div>
<pre><code>## [1] 0.5107943</code></pre>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb118-1" title="1"><span class="kw">exp</span>(<span class="op">-</span><span class="fl">0.10590430</span>) <span class="co"># nodes</span></a></code></pre></div>
<pre><code>## [1] 0.8995107</code></pre>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb120-1" title="1"><span class="kw">exp</span>(<span class="op">-</span><span class="fl">0.43987388</span>) <span class="co"># grade 3</span></a></code></pre></div>
<pre><code>## [1] 0.6441177</code></pre>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb122-1" title="1"><span class="kw">exp</span>(<span class="fl">0.00892277</span>) <span class="co"># age</span></a></code></pre></div>
<pre><code>## [1] 1.008963</code></pre>
<p>Having chemotherapy, hormon-therapy and NaN/Other Treatment is associated with a scaling of mean time till recurrence by 0.69671, 0.6583021 and 0.5594634 respectively, compared to having both chemo and hormon therapies. And the relations here are also insignificant.</p>
<p>Compared to tumor size &lt;=20mm, having tumor size 20-50mm and &gt;50mm will make the expected survival time scaled by 0.6579301 and 0.5107943.</p>
<p>For node and age, each extra positive lymph nodes and every 1-year increase in age is associated with a scaling of mean survival time by 0.8995107 and 1.008963.</p>
<p>And compared to grade II, grade III of cancer cell makes the expected survival time multiplied by 0.6441177.</p>
</div>
</div>
<div id="why-log-normal" class="section level4">
<h4><span class="header-section-number">3.4.3.2</span> Why log-normal</h4>
<p>As to why the Log-normal model would be suitable for the data, we are not sure. One thing to consider is that the non-monotonicity of the hazard function, which is one main characteristic of log-normal model compared to Exponential and Weibull.</p>
<p>The plot below graphs the general hazard functions of our <code>dtime</code> and <code>rtime</code> in a non-parametric way, and we can find that both of them shows non-monotonicity. Though we cannot graph the exact hazard functions conditioning on the diagnostic and treatment information, the non-parametric hazard can still partially explain the adquacy of log-normal.</p>
<p><img src="Cox-Snell/dhazard.png" /></p>
<p><img src="Cox-Snell/rhazard.png" /></p>
</div>
<div id="positive-coefficient-of-age" class="section level4">
<h4><span class="header-section-number">3.4.3.3</span> Positive coefficient of <code>age</code></h4>
<p>In the <code>rtime ~ Treatment + size + nodes + age</code> models, it is surprised to see that the coefficient of <code>age</code> is positive, though the value is small. One possible explanation could be the idea of “competing events” and “competing risk”.</p>
<p>In this scenario, having recurred breast cancer and being dead could be somewhat “competing events”. Though they are not completely “cannot happen on one person at the same time”, it is still reasonable to think that for older patients, it is more likely to die from breast cancer or other complications than being cancer-free for years and then having breast cancer recurred; whereas for younger people, the risk of having recurrent breast cancer could be higher than being dead from the first breast cancer.</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb124-1" title="1">rotterdam_new &lt;-<span class="st"> </span>rotterdam <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb124-2" title="2"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">state =</span> <span class="kw">ifelse</span>(death <span class="op">==</span><span class="st"> </span><span class="dv">1</span> <span class="op">&amp;</span><span class="st"> </span>recur <span class="op">==</span><span class="st"> </span><span class="dv">0</span>, <span class="st">&quot;death&quot;</span>,</a>
<a class="sourceLine" id="cb124-3" title="3">                 <span class="kw">ifelse</span>(death <span class="op">==</span><span class="st"> </span><span class="dv">0</span> <span class="op">&amp;</span><span class="st"> </span>recur <span class="op">==</span><span class="st"> </span><span class="dv">1</span>, <span class="st">&quot;recur&quot;</span>, </a>
<a class="sourceLine" id="cb124-4" title="4">                 <span class="kw">ifelse</span>(death <span class="op">==</span><span class="st"> </span><span class="dv">1</span> <span class="op">&amp;</span><span class="st"> </span>recur <span class="op">==</span><span class="st"> </span><span class="dv">1</span>, <span class="st">&quot;both&quot;</span>, <span class="st">&quot;neither&quot;</span>))))</a>
<a class="sourceLine" id="cb124-5" title="5"></a>
<a class="sourceLine" id="cb124-6" title="6"><span class="kw">ggplot</span>(rotterdam_new, <span class="kw">aes</span>(<span class="dt">x=</span>age, <span class="dt">color=</span>state, <span class="dt">fill=</span>state)) <span class="op">+</span></a>
<a class="sourceLine" id="cb124-7" title="7"><span class="st">  </span><span class="kw">geom_density</span>(<span class="dt">alpha=</span><span class="fl">0.3</span>)</a></code></pre></div>
<p><img src="Rotterdam_files/figure-html/unnamed-chunk-71-1.png" width="672" /></p>
<p>The plot above also helps verifying the idea. We can find that the group who has been dead during the study but has never had breast cancer recurred (the green one) tends to be older than others.</p>
<p>The positive coefficient of <code>age</code> in the log-normal model may seem indicating a protective effect of being old against having breast cancer recurred, but this should not be the true case. It is very likely that this is caused by the competing risk between being dead and having breast cancer recurred for people in different age group. The elderly patients are less likely to suffer from recurrent breast cancer because they are more likely to die from breast cancer or other complications during the treatment after the first diagnosis.</p>
</div>
</div>
</div>
<p style="text-align: center;">
<a href="3-3-kaplan-miere-estimator-on-different-variables-in-rotterdam.html"><button class="btn btn-default">Previous</button></a>
<a href="3-5-cox-ph-model.html"><button class="btn btn-default">Next</button></a>
</p>
</div>
</div>


</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

</body>
</html>
