<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta property="og:title" content="3.5 Cox-PH model: | Rotterdam" />
<meta property="og:type" content="book" />





<meta name="author" content="JACK TAN, YIMING MIAO" />

<meta name="date" content="2021-03-14" />

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS_CHTML-full" type="text/javascript"></script>

<meta name="description" content="3.5 Cox-PH model: | Rotterdam">

<title>3.5 Cox-PH model: | Rotterdam</title>

<script src="libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="libs/navigation-1.1/tabsets.js"></script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<link rel="stylesheet" href="toc.css" type="text/css" />

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
</style>
</head>

<body>

<div class="container-fluid main-container">


<div class="row">
<div class="col-sm-12">
<div id="TOC">
<ul>
<li class="has-sub"><a href="index.html#motivation"><span class="toc-section-number">1</span> Motivation</a><ul>
<li><a href="1-1-some-background-information.html#some-background-information"><span class="toc-section-number">1.1</span> Some Background Information</a></li>
</ul></li>
<li class="has-sub"><a href="2-data-exploration.html#data-exploration"><span class="toc-section-number">2</span> Data Exploration</a><ul>
<li><a href="2-1-loading-data.html#loading-data"><span class="toc-section-number">2.1</span> Loading Data</a></li>
<li class="has-sub"><a href="2-2-data-wrangling.html#data-wrangling"><span class="toc-section-number">2.2</span> Data Wrangling</a><ul>
<li><a href="2-2-data-wrangling.html#ttumornnodemmetastasis"><span class="toc-section-number">2.2.1</span> T(Tumor)N(Node)M(Metastasis)</a></li>
<li><a href="2-2-data-wrangling.html#treatment"><span class="toc-section-number">2.2.2</span> Treatment</a></li>
</ul></li>
<li class="has-sub"><a href="2-3-data-visualizations-and-exploration.html#data-visualizations-and-exploration"><span class="toc-section-number">2.3</span> Data visualizations and exploration</a><ul>
<li><a href="2-3-data-visualizations-and-exploration.html#diagnostics-vs.-survival-times"><span class="toc-section-number">2.3.1</span> Diagnostics vs. Survival Times</a></li>
<li><a href="2-3-data-visualizations-and-exploration.html#treatment-vs.-survival-times"><span class="toc-section-number">2.3.2</span> Treatment vs. Survival Times</a></li>
<li><a href="2-3-data-visualizations-and-exploration.html#age-treatment-vs.-survival-times"><span class="toc-section-number">2.3.3</span> <code>age</code> + <code>Treatment</code> vs. Survival Times</a></li>
<li><a href="2-3-data-visualizations-and-exploration.html#treatment-vs.-tnm"><span class="toc-section-number">2.3.4</span> <code>Treatment</code> vs. TNM</a></li>
<li><a href="2-3-data-visualizations-and-exploration.html#general-x-year-survival-rate"><span class="toc-section-number">2.3.5</span> General X-year Survival Rate</a></li>
</ul></li>
</ul></li>
<li class="has-sub"><a href="3-survival-analysis.html#survival-analysis"><span class="toc-section-number">3</span> Survival Analysis</a><ul>
<li><a href="3-1-notation.html#notation"><span class="toc-section-number">3.1</span> Notation</a></li>
<li><a href="3-2-kaplan-miere-estimator-of-the-entire-dataset.html#kaplan-miere-estimator-of-the-entire-dataset"><span class="toc-section-number">3.2</span> Kaplan-Miere estimator of the entire dataset</a></li>
<li class="has-sub"><a href="3-3-kaplan-miere-estimator-on-different-variables-in-rotterdam.html#kaplan-miere-estimator-on-different-variables-in-rotterdam"><span class="toc-section-number">3.3</span> Kaplan-Miere estimator on different variables in <code>rotterdam</code></a><ul>
<li><a href="3-3-kaplan-miere-estimator-on-different-variables-in-rotterdam.html#size-vs.-survival-times"><span class="toc-section-number">3.3.1</span> <code>size</code> vs. Survival Times</a></li>
<li><a href="3-3-kaplan-miere-estimator-on-different-variables-in-rotterdam.html#nodes_level-vs.-survival-times"><span class="toc-section-number">3.3.2</span> <code>Nodes_level</code> vs. Survival Times</a></li>
<li><a href="3-3-kaplan-miere-estimator-on-different-variables-in-rotterdam.html#grade-vs.-survival-times"><span class="toc-section-number">3.3.3</span> <code>grade</code> vs. Survival Times</a></li>
<li><a href="3-3-kaplan-miere-estimator-on-different-variables-in-rotterdam.html#treatment-vs.-survival-times-1"><span class="toc-section-number">3.3.4</span> <code>Treatment</code> vs. Survival Times</a></li>
</ul></li>
<li class="has-sub"><a href="3-4-parametric-models.html#parametric-models"><span class="toc-section-number">3.4</span> Parametric Models</a><ul>
<li><a href="3-4-parametric-models.html#user-defined-cox-snell-function"><span class="toc-section-number">3.4.1</span> User-defined Cox-Snell function</a></li>
<li><a href="3-4-parametric-models.html#exponential-and-weibull"><span class="toc-section-number">3.4.2</span> Exponential and Weibull</a></li>
<li><a href="3-4-parametric-models.html#log-normal-models"><span class="toc-section-number">3.4.3</span> Log-normal models</a></li>
</ul></li>
<li class="has-sub"><a href="3-5-cox-ph-model.html#cox-ph-model"><span class="toc-section-number">3.5</span> Cox-PH model:</a><ul>
<li><a href="3-5-cox-ph-model.html#cox-ph-model-for-dtime"><span class="toc-section-number">3.5.1</span> Cox-PH model for <code>dtime</code></a></li>
<li><a href="3-5-cox-ph-model.html#cox-ph-model-for-rtime"><span class="toc-section-number">3.5.2</span> Cox-PH model for <code>rtime</code></a></li>
</ul></li>
<li><a href="3-6-summary.html#summary"><span class="toc-section-number">3.6</span> Summary</a></li>
</ul></li>
<li class="has-sub"><a href="4-random-survival-forest.html#random-survival-forest"><span class="toc-section-number">4</span> Random Survival Forest</a><ul>
<li><a href="4-1-dtime.html#dtime"><span class="toc-section-number">4.1</span> <code>dtime</code></a></li>
<li><a href="4-2-rtime.html#rtime"><span class="toc-section-number">4.2</span> <code>rtime</code></a></li>
</ul></li>
<li class="has-sub"><a href="5-conclusion.html#conclusion"><span class="toc-section-number">5</span> Conclusion</a><ul>
<li><a href="5-1-limitation.html#limitation"><span class="toc-section-number">5.1</span> Limitation</a></li>
<li><a href="5-2-reference.html#reference"><span class="toc-section-number">5.2</span> Reference</a></li>
</ul></li>
</ul>
</div>
</div>
</div>
<div class="row">
<div class="col-sm-12">
<div id="cox-ph-model" class="section level2">
<h2><span class="header-section-number">3.5</span> Cox-PH model:</h2>
<p>Another very important part of a survival analysis is looking for the hazard ratio by building and interpreting the coxph model.</p>
<p>Cox’s PH model assumes that the hazard function for any subject can be written as: <span class="math inline">\(h(t) = h_0(t)e^{b_1 x_1 + b_2 x_2 + \dots + b_k x_k}\)</span>,
where <span class="math inline">\(h_0(t)\)</span> is called a baseline hazard function, and the <span class="math inline">\(x_i\)</span>’s are covariates. The Cox PH model assumes that, for any 2 values
of a covariate, the hazard ratio (HR) is constant over time.</p>
<p>With this model, once we have proof of the validation of the PH assumption of the model, we could have nice coefficients to interpret as the logarithm of HR(hazard ratio) among different groups. We will be following the way that we built our parametric models, by using Survival times vs. <code>age</code> + <code>size</code> + <code>nodes</code> + <code>grade</code> + <code>Treatment</code>.</p>
<div id="cox-ph-model-for-dtime" class="section level3">
<h3><span class="header-section-number">3.5.1</span> Cox-PH model for <code>dtime</code></h3>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb125-1" title="1">m_death_withage =<span class="st"> </span><span class="kw">coxph</span>(<span class="kw">Surv</span>(dtime, death) <span class="op">~</span><span class="st"> </span>Treatment <span class="op">+</span><span class="st"> </span>size <span class="op">+</span><span class="st"> </span>nodes <span class="op">+</span><span class="st"> </span>grade <span class="op">+</span><span class="st"> </span>age, <span class="dt">data=</span>rotterdam)</a>
<a class="sourceLine" id="cb125-2" title="2">m_death_withage</a></code></pre></div>
<pre><code>## Call:
## coxph(formula = Surv(dtime, death) ~ Treatment + size + nodes + 
##     grade + age, data = rotterdam)
## 
##                                  coef exp(coef) se(coef)      z        p
## TreatmentChemo               0.544967  1.724551 0.360119  1.513    0.130
## TreatmentHormon              0.488511  1.629887 0.366267  1.334    0.182
## TreatmentNaN/Other Treatment 0.491504  1.634773 0.356997  1.377    0.169
## size20-50                    0.450933  1.569776 0.065260  6.910 4.85e-12
## size&gt;50                      0.818215  2.266451 0.091189  8.973  &lt; 2e-16
## nodes                        0.073329  1.076085 0.004865 15.072  &lt; 2e-16
## grade3                       0.350976  1.420453 0.070141  5.004 5.62e-07
## age                          0.015067  1.015182 0.002552  5.903 3.56e-09
## 
## Likelihood ratio test=513.7  on 8 df, p=&lt; 2.2e-16
## n= 2982, number of events= 1272</code></pre>
<p>First we should check if the PH assumption holds. We will be using a formal test.</p>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb127-1" title="1"><span class="kw">cox.zph</span>(m_death_withage)</a></code></pre></div>
<pre><code>##           chisq df       p
## Treatment  4.32  3 0.22855
## size       4.71  2 0.09487
## nodes      3.87  1 0.04915
## grade      2.61  1 0.10637
## age       14.48  1 0.00014
## GLOBAL    26.91  8 0.00073</code></pre>
<p>There are two variables, <code>age</code> and <code>nodes</code>, that have have p-value smaller than 0.05, which indicates the violation of the PH assumption.</p>
<p>One way we came up to solve this problem is to put stratification on <code>age</code> and <code>nodes</code> by putting a <code>strata()</code> on them when fitting the model. What this does is to recognize the correlation between <code>age</code> and <code>dtime</code> and <code>nodes</code> and <code>dtime</code>, but not actually including them in our model results.</p>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb129-1" title="1">m_death_strataage =<span class="st"> </span><span class="kw">coxph</span>(<span class="kw">Surv</span>(dtime, death) <span class="op">~</span><span class="st"> </span>Treatment <span class="op">+</span><span class="st"> </span>size <span class="op">+</span><span class="st"> </span><span class="kw">strata</span>(nodes) <span class="op">+</span><span class="st"> </span>grade <span class="op">+</span><span class="st"> </span><span class="kw">strata</span>(age), <span class="dt">data=</span>rotterdam)</a>
<a class="sourceLine" id="cb129-2" title="2">m_death_strataage</a></code></pre></div>
<pre><code>## Call:
## coxph(formula = Surv(dtime, death) ~ Treatment + size + strata(nodes) + 
##     grade + strata(age), data = rotterdam)
## 
##                                 coef exp(coef) se(coef)     z        p
## TreatmentChemo               0.45621   1.57808  0.47456 0.961    0.336
## TreatmentHormon              0.44920   1.56706  0.49904 0.900    0.368
## TreatmentNaN/Other Treatment 0.76097   2.14035  0.48430 1.571    0.116
## size20-50                    0.43163   1.53977  0.08021 5.381 7.40e-08
## size&gt;50                      0.63412   1.88536  0.14221 4.459 8.23e-06
## grade3                       0.38089   1.46358  0.09141 4.167 3.09e-05
## 
## Likelihood ratio test=67.3  on 6 df, p=1.459e-12
## n= 2982, number of events= 1272</code></pre>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb131-1" title="1"><span class="kw">cox.zph</span>(m_death_strataage)</a></code></pre></div>
<pre><code>##           chisq df    p
## Treatment 3.198  3 0.36
## size      1.819  2 0.40
## grade     0.635  1 0.43
## GLOBAL    5.791  6 0.45</code></pre>
<p>Now we can see that all the variables’ p-value are greater than 0.05 which indicates the PH assumption holds in our model.</p>
<p>For treatments, we can see that Chemotherapy, Hormontherapy and Other Treatment all have higher risks than patients receiving both therapies, with hazard ratio 1.57808, 1.56706 and 2.14035 respectively. However, note that all three p-values are greater than 0.05, which means that we do not have significant evidence for such relationships.</p>
<p>And for size, it is clear that patients with larger tumor size enjoy higher risks, and as the size grows, the risk is also increasing, with hazard ratio 1.53977 and 1.88536 for 20-50mm vs. &lt;=20mm and &gt;50mm vs. &lt;=20mm. Such relationship is significant as we can see from the p-values since they are all less than 0.05.</p>
<p>For grade, we could see that the risk is going to be multiplied by 1.46358, if it goes from grade II to grade III, and the relation is staitstically significant.</p>
</div>
<div id="cox-ph-model-for-rtime" class="section level3">
<h3><span class="header-section-number">3.5.2</span> Cox-PH model for <code>rtime</code></h3>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb133-1" title="1">m_recur =<span class="st"> </span><span class="kw">coxph</span>(<span class="kw">Surv</span>(rtime, recur) <span class="op">~</span><span class="st"> </span>Treatment <span class="op">+</span><span class="st"> </span><span class="kw">strata</span>(size) <span class="op">+</span><span class="st"> </span><span class="kw">strata</span>(nodes) <span class="op">+</span><span class="st"> </span><span class="kw">strata</span>(grade) <span class="op">+</span><span class="st"> </span>age, <span class="dt">data=</span>rotterdam)</a>
<a class="sourceLine" id="cb133-2" title="2">m_recur</a></code></pre></div>
<pre><code>## Call:
## coxph(formula = Surv(rtime, recur) ~ Treatment + strata(size) + 
##     strata(nodes) + strata(grade) + age, data = rotterdam)
## 
##                                   coef exp(coef)  se(coef)      z        p
## TreatmentChemo                0.280433  1.323703  0.290152  0.967  0.33379
## TreatmentHormon               0.396060  1.485958  0.300374  1.319  0.18732
## TreatmentNaN/Other Treatment  0.817338  2.264464  0.291876  2.800  0.00511
## age                          -0.015377  0.984741  0.002553 -6.023 1.71e-09
## 
## Likelihood ratio test=63.27  on 4 df, p=5.96e-13
## n= 2982, number of events= 1518</code></pre>
<p>For <code>rtime</code>, we found that all the diagnostic information <code>size</code>, <code>nodes</code> and <code>grade</code> obeys the PH assumption, and we can only investigate <code>Treatment</code> and <code>age</code>.</p>
<p>We can find that patients taking both chemo and hormon therapies still have lowest hazard of breast cancer recurrence, and having chemo only, hormon only or NaN/Other Treatment will multiply the hazard by 1.323703, 1.485958 and 2.264464 respectively. However, the statistical significance is not that strong.</p>
<p>And for age, it’s still surprised to see that its coefficient is negative, indicating that every 1-year increase in age will make the hazard of breast cancer recurrence by 0.984741. The reason behind this should be the same as the idea of competing risk we mentioned above.</p>
</div>
</div>
<p style="text-align: center;">
<a href="3-4-parametric-models.html"><button class="btn btn-default">Previous</button></a>
<a href="3-6-summary.html"><button class="btn btn-default">Next</button></a>
</p>
</div>
</div>


</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

</body>
</html>
