<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter3 Survival | Rotterdam</title>
  <meta name="description" content="Chapter3 Survival | Rotterdam" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter3 Survival | Rotterdam" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter3 Survival | Rotterdam" />
  
  
  

<meta name="author" content="JACK TAN, YIMING MIAO" />


<meta name="date" content="2021-03-12" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="data-exploration.html"/>
<link rel="next" href="conclusion.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Motivation</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#some-background-information"><i class="fa fa-check"></i><b>1.1</b> Some Background Information</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="data-exploration.html"><a href="data-exploration.html"><i class="fa fa-check"></i><b>2</b> Data Exploration</a><ul>
<li class="chapter" data-level="2.1" data-path="data-exploration.html"><a href="data-exploration.html#loading-data"><i class="fa fa-check"></i><b>2.1</b> Loading Data</a></li>
<li class="chapter" data-level="2.2" data-path="data-exploration.html"><a href="data-exploration.html#data-wrangling"><i class="fa fa-check"></i><b>2.2</b> Data Wrangling</a><ul>
<li class="chapter" data-level="2.2.1" data-path="data-exploration.html"><a href="data-exploration.html#ttumornnodemmetastasis"><i class="fa fa-check"></i><b>2.2.1</b> T(Tumor)N(Node)M(Metastasis)</a></li>
<li class="chapter" data-level="2.2.2" data-path="data-exploration.html"><a href="data-exploration.html#treatment"><i class="fa fa-check"></i><b>2.2.2</b> Treatment</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="data-exploration.html"><a href="data-exploration.html#data-visualizations-and-exploration"><i class="fa fa-check"></i><b>2.3</b> Data visualizations and exploration</a><ul>
<li class="chapter" data-level="2.3.1" data-path="data-exploration.html"><a href="data-exploration.html#diagnostics-vs.-survival-times"><i class="fa fa-check"></i><b>2.3.1</b> Diagnostics vs. Survival Times</a></li>
<li class="chapter" data-level="2.3.2" data-path="data-exploration.html"><a href="data-exploration.html#treatment-vs.-survival-times"><i class="fa fa-check"></i><b>2.3.2</b> Treatment vs. Survival Times</a></li>
<li class="chapter" data-level="2.3.3" data-path="data-exploration.html"><a href="data-exploration.html#age-treatment-vs.-survival-times"><i class="fa fa-check"></i><b>2.3.3</b> <code>age</code> + <code>Treatment</code> vs. Survival Times</a></li>
<li class="chapter" data-level="2.3.4" data-path="data-exploration.html"><a href="data-exploration.html#treatment-vs.-tnm"><i class="fa fa-check"></i><b>2.3.4</b> <code>Treatment</code> vs. TNM</a></li>
<li class="chapter" data-level="2.3.5" data-path="data-exploration.html"><a href="data-exploration.html#general-x-year-survival-rate"><i class="fa fa-check"></i><b>2.3.5</b> General X-year Survival Rate</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="survival.html"><a href="survival.html"><i class="fa fa-check"></i><b>3</b> Survival</a><ul>
<li class="chapter" data-level="3.1" data-path="survival.html"><a href="survival.html#loading-data-1"><i class="fa fa-check"></i><b>3.1</b> Loading Data</a></li>
<li class="chapter" data-level="3.2" data-path="survival.html"><a href="survival.html#kaplan-miere-estimator-of-the-entire-dataset"><i class="fa fa-check"></i><b>3.2</b> Kaplan-Miere estimator of the entire dataset</a></li>
<li class="chapter" data-level="3.3" data-path="survival.html"><a href="survival.html#kaplan-miere-estimator-on-different-variables-in-rotterdam"><i class="fa fa-check"></i><b>3.3</b> Kaplan-Miere estimator on different variables in <code>rotterdam</code></a><ul>
<li class="chapter" data-level="3.3.1" data-path="survival.html"><a href="survival.html#size-vs.-survival-times"><i class="fa fa-check"></i><b>3.3.1</b> <code>size</code> vs. Survival Times</a></li>
<li class="chapter" data-level="3.3.2" data-path="survival.html"><a href="survival.html#nodes_level-vs.-survival-times"><i class="fa fa-check"></i><b>3.3.2</b> <code>Nodes_level</code> vs. Survival Times</a></li>
<li class="chapter" data-level="3.3.3" data-path="survival.html"><a href="survival.html#treatment-vs.-survival-times-1"><i class="fa fa-check"></i><b>3.3.3</b> <code>Treatment</code> vs. Survival Times</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="survival.html"><a href="survival.html#parametric-models"><i class="fa fa-check"></i><b>3.4</b> Parametric Models</a><ul>
<li class="chapter" data-level="3.4.1" data-path="survival.html"><a href="survival.html#user-defined-cox-snell-function"><i class="fa fa-check"></i><b>3.4.1</b> User-defined Cox-Snell function</a></li>
<li class="chapter" data-level="3.4.2" data-path="survival.html"><a href="survival.html#exponential-models"><i class="fa fa-check"></i><b>3.4.2</b> Exponential models</a></li>
<li class="chapter" data-level="3.4.3" data-path="survival.html"><a href="survival.html#weibull-models"><i class="fa fa-check"></i><b>3.4.3</b> Weibull models</a></li>
<li class="chapter" data-level="3.4.4" data-path="survival.html"><a href="survival.html#log-normal-models"><i class="fa fa-check"></i><b>3.4.4</b> Log-normal models</a></li>
<li class="chapter" data-level="3.4.5" data-path="survival.html"><a href="survival.html#positive-coefficient-of-age"><i class="fa fa-check"></i><b>3.4.5</b> Positive coefficient of <code>age</code></a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="survival.html"><a href="survival.html#cox-ph-model"><i class="fa fa-check"></i><b>3.5</b> Cox-PH model:</a><ul>
<li class="chapter" data-level="3.5.1" data-path="survival.html"><a href="survival.html#dtime-coxph-model"><i class="fa fa-check"></i><b>3.5.1</b> <code>dtime</code> coxph model</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="conclusion.html"><a href="conclusion.html"><i class="fa fa-check"></i><b>4</b> Conclusion</a><ul>
<li class="chapter" data-level="4.1" data-path="conclusion.html"><a href="conclusion.html#limitation"><i class="fa fa-check"></i><b>4.1</b> Limitation</a></li>
<li class="chapter" data-level="4.2" data-path="conclusion.html"><a href="conclusion.html#reference"><i class="fa fa-check"></i><b>4.2</b> Reference</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Rotterdam</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="survival" class="section level1">
<h1><span class="header-section-number">Chapter3</span> Survival</h1>
<div id="loading-data-1" class="section level2">
<h2><span class="header-section-number">3.1</span> Loading Data</h2>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb40-1" title="1"><span class="kw">data</span>(rotterdam)</a></code></pre></div>
</div>
<div id="kaplan-miere-estimator-of-the-entire-dataset" class="section level2">
<h2><span class="header-section-number">3.2</span> Kaplan-Miere estimator of the entire dataset</h2>
<p>Death Time</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb41-1" title="1">KM &lt;-<span class="st"> </span><span class="kw">survfit</span>(<span class="kw">Surv</span>(dtime, death) <span class="op">~</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">data =</span> rotterdam)</a>
<a class="sourceLine" id="cb41-2" title="2"><span class="kw">plot</span>(KM, <span class="dt">conf.int =</span> <span class="ot">TRUE</span>, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">xlab=</span><span class="st">&quot;Days&quot;</span>, <span class="dt">ylab=</span><span class="st">&quot;Survival&quot;</span>)</a></code></pre></div>
<p><img src="Rotterdam_files/figure-html/unnamed-chunk-34-1.png" width="672" /></p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb42-1" title="1"><span class="kw">mean</span>(rotterdam<span class="op">$</span>dtime)</a></code></pre></div>
<pre><code>## [1] 2605.34</code></pre>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb44-1" title="1"><span class="kw">median</span>(rotterdam<span class="op">$</span>dtime)</a></code></pre></div>
<pre><code>## [1] 2638.5</code></pre>
<p>The overall mean survival time till death for breast cancer is 2605 days, which is approximately 7 years. The overall median survival time till death for breast cancer is 2638 days, which is also approximately 7 years.</p>
<p>Recurrence Time</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb46-1" title="1">KM &lt;-<span class="st"> </span><span class="kw">survfit</span>(<span class="kw">Surv</span>(rtime, recur) <span class="op">~</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">data =</span> rotterdam)</a>
<a class="sourceLine" id="cb46-2" title="2"><span class="kw">plot</span>(KM, <span class="dt">conf.int =</span> <span class="ot">TRUE</span>, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">xlab=</span><span class="st">&quot;Days&quot;</span>, <span class="dt">ylab=</span><span class="st">&quot;Survival&quot;</span>)</a></code></pre></div>
<p><img src="Rotterdam_files/figure-html/unnamed-chunk-36-1.png" width="672" /></p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb47-1" title="1"><span class="kw">mean</span>(rotterdam<span class="op">$</span>rtime)</a></code></pre></div>
<pre><code>## [1] 2097.903</code></pre>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb49-1" title="1"><span class="kw">median</span>(rotterdam<span class="op">$</span>rtime)</a></code></pre></div>
<pre><code>## [1] 1940</code></pre>
<p>The overall mean survival time till recurrence for breast cancer is 2097 days, which is approximately 6 years. The overall median survival time till recurrence for breast cancer is 1940 days, which is also approximately 5 years.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb51-1" title="1">KM &lt;-<span class="st"> </span><span class="kw">survfit</span>(<span class="kw">Surv</span>(drecurtime, death) <span class="op">~</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">data =</span> rotterdam_recur)</a>
<a class="sourceLine" id="cb51-2" title="2"><span class="kw">plot</span>(KM, <span class="dt">conf.int =</span> <span class="ot">TRUE</span>, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">xlab=</span><span class="st">&quot;Days&quot;</span>, <span class="dt">ylab=</span><span class="st">&quot;Survival&quot;</span>)</a></code></pre></div>
<p><img src="Rotterdam_files/figure-html/unnamed-chunk-38-1.png" width="672" /></p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb52-1" title="1"><span class="kw">mean</span>(rotterdam_recur<span class="op">$</span>drecurtime)</a></code></pre></div>
<pre><code>## [1] 978.5481</code></pre>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb54-1" title="1"><span class="kw">median</span>(rotterdam_recur<span class="op">$</span>drecurtime)</a></code></pre></div>
<pre><code>## [1] 719.5</code></pre>
<p>The overall mean survival time after rucurrence till death for breast cancer is 834 days, which is approximately a little more than 2 years. The overall median survival time after rucurrence till death for breast cancer is 625 days, which is approximately less than 2 years.</p>
<p>Since a Kaplan-Miere estimator is unbiased, we could view the median as being very close to the true value of survival time.</p>
</div>
<div id="kaplan-miere-estimator-on-different-variables-in-rotterdam" class="section level2">
<h2><span class="header-section-number">3.3</span> Kaplan-Miere estimator on different variables in <code>rotterdam</code></h2>
<p>There are 16 variables in the <code>rotterdam</code> dataset. Of course we could have fit each variable with a KM estimator, but it would be meaningless to do them all. We will stick to the Diagnostics and Treatment we mentioned in Chapter 2 and fit <code>size</code>, <code>Nodes_level</code>(we are not using nodes because a Kaplan-Miere estimator does not work well with quantitative variables), and <code>Treatment</code> each with KM estimators with respect to <code>dtime</code>, <code>rtime</code>, and <code>drecurtime</code> to grasp the survival time within each categories of the variables.</p>
<div id="size-vs.-survival-times" class="section level3">
<h3><span class="header-section-number">3.3.1</span> <code>size</code> vs. Survival Times</h3>
<p><code>size</code> vs. <code>dtime</code></p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb56-1" title="1">KM_None_Death &lt;-<span class="st"> </span><span class="kw">survfit</span>(<span class="kw">Surv</span>(dtime, death) <span class="op">~</span><span class="st"> </span>size, <span class="dt">data =</span> rotterdam)</a>
<a class="sourceLine" id="cb56-2" title="2"><span class="kw">plot</span>(KM_None_Death, <span class="dt">conf.type =</span> <span class="st">&quot;plain&quot;</span>, <span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;black&quot;</span>,<span class="st">&quot;red&quot;</span>,<span class="st">&quot;blue&quot;</span>), <span class="dt">xlab=</span><span class="st">&quot;Days&quot;</span>, <span class="dt">ylab=</span><span class="st">&quot;Survival&quot;</span>)</a>
<a class="sourceLine" id="cb56-3" title="3"><span class="kw">legend</span>(<span class="dv">6000</span>, <span class="dv">1</span>, <span class="dt">legend=</span><span class="kw">c</span>(<span class="st">&quot;&lt;=20&quot;</span>, <span class="st">&quot;20-50&quot;</span>, <span class="st">&quot;&gt;50&quot;</span>),</a>
<a class="sourceLine" id="cb56-4" title="4">       <span class="dt">col=</span><span class="kw">c</span>(<span class="st">&quot;black&quot;</span>, <span class="st">&quot;red&quot;</span>, <span class="st">&quot;blue&quot;</span>), <span class="dt">lty=</span><span class="dv">1</span>, <span class="dt">cex=</span><span class="fl">0.8</span>,</a>
<a class="sourceLine" id="cb56-5" title="5">       <span class="dt">title=</span><span class="st">&quot;Tumor Size&quot;</span>, <span class="dt">text.font=</span><span class="dv">6</span>)</a></code></pre></div>
<p><img src="Rotterdam_files/figure-html/unnamed-chunk-40-1.png" width="672" /></p>
<p><code>size</code> vs. <code>rtime</code></p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb57-1" title="1">KM_None_Recur &lt;-<span class="st"> </span><span class="kw">survfit</span>(<span class="kw">Surv</span>(rtime, recur) <span class="op">~</span><span class="st"> </span>size, <span class="dt">data =</span> rotterdam)</a>
<a class="sourceLine" id="cb57-2" title="2"><span class="kw">plot</span>(KM_None_Recur, <span class="dt">conf.type =</span> <span class="st">&quot;plain&quot;</span>, <span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;black&quot;</span>,<span class="st">&quot;red&quot;</span>,<span class="st">&quot;blue&quot;</span>), <span class="dt">xlab=</span><span class="st">&quot;Days&quot;</span>, <span class="dt">ylab=</span><span class="st">&quot;Survival&quot;</span>)</a>
<a class="sourceLine" id="cb57-3" title="3"><span class="kw">legend</span>(<span class="dv">6000</span>, <span class="dv">1</span>, <span class="dt">legend=</span><span class="kw">c</span>(<span class="st">&quot;&lt;=20&quot;</span>, <span class="st">&quot;20-50&quot;</span>, <span class="st">&quot;&gt;50&quot;</span>),</a>
<a class="sourceLine" id="cb57-4" title="4">       <span class="dt">col=</span><span class="kw">c</span>(<span class="st">&quot;black&quot;</span>, <span class="st">&quot;red&quot;</span>, <span class="st">&quot;blue&quot;</span>), <span class="dt">lty=</span><span class="dv">1</span>, <span class="dt">cex=</span><span class="fl">0.8</span>,</a>
<a class="sourceLine" id="cb57-5" title="5">       <span class="dt">title=</span><span class="st">&quot;Tumor Size&quot;</span>, <span class="dt">text.font=</span><span class="dv">6</span>)</a></code></pre></div>
<p><img src="Rotterdam_files/figure-html/unnamed-chunk-41-1.png" width="672" /></p>
<p>In general, patients with smaller tumor at diagnosis enjoys longer survival for both death and recurrence.</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb58-1" title="1">KM_None_drecur &lt;-<span class="st"> </span><span class="kw">survfit</span>(<span class="kw">Surv</span>(drecurtime, death) <span class="op">~</span><span class="st"> </span>size, <span class="dt">data =</span> rotterdam_recur)</a>
<a class="sourceLine" id="cb58-2" title="2"><span class="kw">plot</span>(KM_None_drecur, <span class="dt">conf.type =</span> <span class="st">&quot;plain&quot;</span>, <span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;black&quot;</span>,<span class="st">&quot;red&quot;</span>,<span class="st">&quot;blue&quot;</span>), <span class="dt">xlab=</span><span class="st">&quot;Days&quot;</span>, <span class="dt">ylab=</span><span class="st">&quot;Survival&quot;</span>)</a>
<a class="sourceLine" id="cb58-3" title="3"><span class="kw">legend</span>(<span class="dv">4500</span>, <span class="dv">1</span>, <span class="dt">legend=</span><span class="kw">c</span>(<span class="st">&quot;&lt;=20&quot;</span>, <span class="st">&quot;20-50&quot;</span>, <span class="st">&quot;&gt;50&quot;</span>),</a>
<a class="sourceLine" id="cb58-4" title="4">       <span class="dt">col=</span><span class="kw">c</span>(<span class="st">&quot;black&quot;</span>, <span class="st">&quot;red&quot;</span>, <span class="st">&quot;blue&quot;</span>), <span class="dt">lty=</span><span class="dv">1</span>, <span class="dt">cex=</span><span class="fl">0.8</span>,</a>
<a class="sourceLine" id="cb58-5" title="5">       <span class="dt">title=</span><span class="st">&quot;Tumor Size&quot;</span>, <span class="dt">text.font=</span><span class="dv">6</span>)</a></code></pre></div>
<p><img src="Rotterdam_files/figure-html/unnamed-chunk-42-1.png" width="672" /></p>
<p>The trend is still the same as patients with smaller tumor size enjoy longer survival of death after recurrence, but the survival time now decreases much faster for all groups.</p>
</div>
<div id="nodes_level-vs.-survival-times" class="section level3">
<h3><span class="header-section-number">3.3.2</span> <code>Nodes_level</code> vs. Survival Times</h3>
<p><code>Nodes_level</code> vs. <code>dtime</code></p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb59-1" title="1">KM_None_Death &lt;-<span class="st"> </span><span class="kw">survfit</span>(<span class="kw">Surv</span>(dtime, death) <span class="op">~</span><span class="st"> </span>Nodes_level, <span class="dt">data =</span> rotterdam)</a>
<a class="sourceLine" id="cb59-2" title="2"><span class="kw">plot</span>(KM_None_Death, <span class="dt">conf.type =</span> <span class="st">&quot;plain&quot;</span>, <span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;black&quot;</span>,<span class="st">&quot;red&quot;</span>,<span class="st">&quot;blue&quot;</span>,<span class="st">&quot;orange&quot;</span>), <span class="dt">xlab=</span><span class="st">&quot;Days&quot;</span>, <span class="dt">ylab=</span><span class="st">&quot;Survival&quot;</span>)</a>
<a class="sourceLine" id="cb59-3" title="3"><span class="kw">legend</span>(<span class="dv">6000</span>, <span class="dv">1</span>, <span class="dt">legend=</span><span class="kw">c</span>(<span class="st">&quot;N0&quot;</span>, <span class="st">&quot;N1&quot;</span>,<span class="st">&quot;N2&quot;</span>, <span class="st">&quot;N3&quot;</span>),</a>
<a class="sourceLine" id="cb59-4" title="4">       <span class="dt">col=</span><span class="kw">c</span>(<span class="st">&quot;black&quot;</span>, <span class="st">&quot;red&quot;</span>, <span class="st">&quot;blue&quot;</span>, <span class="st">&quot;orange&quot;</span>), <span class="dt">lty=</span><span class="dv">1</span>, <span class="dt">cex=</span><span class="fl">0.8</span>,</a>
<a class="sourceLine" id="cb59-5" title="5">       <span class="dt">title=</span><span class="st">&quot;Nodes_level&quot;</span>, <span class="dt">text.font=</span><span class="dv">6</span>)</a></code></pre></div>
<p><img src="Rotterdam_files/figure-html/unnamed-chunk-43-1.png" width="672" /></p>
<p><code>Nodes_level</code> vs. <code>rtime</code></p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb60-1" title="1">KM_None_Recur &lt;-<span class="st"> </span><span class="kw">survfit</span>(<span class="kw">Surv</span>(rtime, recur) <span class="op">~</span><span class="st"> </span>Nodes_level, <span class="dt">data =</span> rotterdam)</a>
<a class="sourceLine" id="cb60-2" title="2"><span class="kw">plot</span>(KM_None_Recur, <span class="dt">conf.type =</span> <span class="st">&quot;plain&quot;</span>, <span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;black&quot;</span>,<span class="st">&quot;red&quot;</span>,<span class="st">&quot;blue&quot;</span>,<span class="st">&quot;orange&quot;</span>), <span class="dt">xlab=</span><span class="st">&quot;Days&quot;</span>, <span class="dt">ylab=</span><span class="st">&quot;Survival&quot;</span>)</a>
<a class="sourceLine" id="cb60-3" title="3"><span class="kw">legend</span>(<span class="dv">6000</span>, <span class="dv">1</span>, <span class="dt">legend=</span><span class="kw">c</span>(<span class="st">&quot;N0&quot;</span>, <span class="st">&quot;N1&quot;</span>,<span class="st">&quot;N2&quot;</span>, <span class="st">&quot;N3&quot;</span>),</a>
<a class="sourceLine" id="cb60-4" title="4">       <span class="dt">col=</span><span class="kw">c</span>(<span class="st">&quot;black&quot;</span>, <span class="st">&quot;red&quot;</span>, <span class="st">&quot;blue&quot;</span>, <span class="st">&quot;orange&quot;</span>), <span class="dt">lty=</span><span class="dv">1</span>, <span class="dt">cex=</span><span class="fl">0.8</span>,</a>
<a class="sourceLine" id="cb60-5" title="5">       <span class="dt">title=</span><span class="st">&quot;Nodes_level&quot;</span>, <span class="dt">text.font=</span><span class="dv">6</span>)</a></code></pre></div>
<p><img src="Rotterdam_files/figure-html/unnamed-chunk-44-1.png" width="672" /></p>
<p>In general, patients with less nodes tested positive will enjoy longer survival for both death and recurrence.</p>
<p><code>Nodes_level</code> vs. <code>drecurtime</code></p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb61-1" title="1">KM_None_drecur &lt;-<span class="st"> </span><span class="kw">survfit</span>(<span class="kw">Surv</span>(drecurtime, death) <span class="op">~</span><span class="st"> </span>Nodes_level, <span class="dt">data =</span> rotterdam_recur)</a>
<a class="sourceLine" id="cb61-2" title="2"><span class="kw">plot</span>(KM_None_drecur, <span class="dt">conf.type =</span> <span class="st">&quot;plain&quot;</span>, <span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;black&quot;</span>,<span class="st">&quot;red&quot;</span>,<span class="st">&quot;blue&quot;</span>,<span class="st">&quot;orange&quot;</span>), <span class="dt">xlab=</span><span class="st">&quot;Days&quot;</span>, <span class="dt">ylab=</span><span class="st">&quot;Survival&quot;</span>)</a>
<a class="sourceLine" id="cb61-3" title="3"><span class="kw">legend</span>(<span class="dv">4500</span>, <span class="dv">1</span>, <span class="dt">legend=</span><span class="kw">c</span>(<span class="st">&quot;N0&quot;</span>, <span class="st">&quot;N1&quot;</span>,<span class="st">&quot;N2&quot;</span>, <span class="st">&quot;N3&quot;</span>),</a>
<a class="sourceLine" id="cb61-4" title="4">       <span class="dt">col=</span><span class="kw">c</span>(<span class="st">&quot;black&quot;</span>, <span class="st">&quot;red&quot;</span>, <span class="st">&quot;blue&quot;</span>, <span class="st">&quot;orange&quot;</span>), <span class="dt">lty=</span><span class="dv">1</span>, <span class="dt">cex=</span><span class="fl">0.8</span>,</a>
<a class="sourceLine" id="cb61-5" title="5">       <span class="dt">title=</span><span class="st">&quot;Nodes_level&quot;</span>, <span class="dt">text.font=</span><span class="dv">6</span>)</a></code></pre></div>
<p><img src="Rotterdam_files/figure-html/unnamed-chunk-45-1.png" width="672" /></p>
<p>The trend is still the same as patients with fewer nodes tested positive enjoy longer survival of death after recurrence, but the survival time now decreases much faster for all groups, and the difference is small in groups <code>N1</code>, <code>N2</code> and <code>N3</code>.</p>
</div>
<div id="treatment-vs.-survival-times-1" class="section level3">
<h3><span class="header-section-number">3.3.3</span> <code>Treatment</code> vs. Survival Times</h3>
<p><code>Treatment</code> vs. <code>dtime</code></p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb62-1" title="1">KM_Treatment_Death &lt;-<span class="st"> </span><span class="kw">survfit</span>(<span class="kw">Surv</span>(dtime, death) <span class="op">~</span><span class="st"> </span>Treatment, <span class="dt">data =</span> rotterdam)</a>
<a class="sourceLine" id="cb62-2" title="2"><span class="kw">plot</span>(KM_Treatment_Death, <span class="dt">conf.int =</span> <span class="ot">FALSE</span>, <span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;black&quot;</span>, <span class="st">&quot;red&quot;</span>, <span class="st">&quot;blue&quot;</span>, <span class="st">&quot;orange&quot;</span>), <span class="dt">xlab=</span><span class="st">&quot;Days&quot;</span>, <span class="dt">ylab=</span><span class="st">&quot;Survival&quot;</span>)</a>
<a class="sourceLine" id="cb62-3" title="3"><span class="kw">legend</span>(<span class="dv">1</span>, <span class="fl">0.4</span>, <span class="dt">legend=</span><span class="kw">c</span>(<span class="st">&quot;Both&quot;</span>, <span class="st">&quot;Chemo&quot;</span>,<span class="st">&quot;Hormon&quot;</span>, <span class="st">&quot;NaN/Other Treatment&quot;</span>),</a>
<a class="sourceLine" id="cb62-4" title="4">       <span class="dt">col=</span><span class="kw">c</span>(<span class="st">&quot;black&quot;</span>, <span class="st">&quot;red&quot;</span>, <span class="st">&quot;blue&quot;</span>, <span class="st">&quot;orange&quot;</span>), <span class="dt">lty=</span><span class="dv">1</span>, <span class="dt">cex=</span><span class="fl">0.8</span>,</a>
<a class="sourceLine" id="cb62-5" title="5">       <span class="dt">title=</span><span class="st">&quot;Treatment Group&quot;</span>, <span class="dt">text.font=</span><span class="dv">6</span>)</a></code></pre></div>
<p><img src="Rotterdam_files/figure-html/unnamed-chunk-46-1.png" width="672" /></p>
<p><code>Treatment</code> vs. <code>rtime</code></p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb63-1" title="1">KM_Treatment_Recur &lt;-<span class="st"> </span><span class="kw">survfit</span>(<span class="kw">Surv</span>(rtime, recur) <span class="op">~</span><span class="st"> </span>Treatment, <span class="dt">data =</span> rotterdam)</a>
<a class="sourceLine" id="cb63-2" title="2"><span class="kw">plot</span>(KM_Treatment_Recur, <span class="dt">conf.int =</span> <span class="ot">FALSE</span>, <span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;black&quot;</span>, <span class="st">&quot;red&quot;</span>, <span class="st">&quot;blue&quot;</span>, <span class="st">&quot;orange&quot;</span>), <span class="dt">xlab=</span><span class="st">&quot;Days&quot;</span>, <span class="dt">ylab=</span><span class="st">&quot;Survival&quot;</span>)</a>
<a class="sourceLine" id="cb63-3" title="3"><span class="kw">legend</span>(<span class="dv">1</span>, <span class="fl">0.4</span>, <span class="dt">legend=</span><span class="kw">c</span>(<span class="st">&quot;Both&quot;</span>, <span class="st">&quot;Chemo&quot;</span>,<span class="st">&quot;Hormon&quot;</span>, <span class="st">&quot;NaN/Other Treatment&quot;</span>),</a>
<a class="sourceLine" id="cb63-4" title="4">       <span class="dt">col=</span><span class="kw">c</span>(<span class="st">&quot;black&quot;</span>, <span class="st">&quot;red&quot;</span>, <span class="st">&quot;blue&quot;</span>, <span class="st">&quot;orange&quot;</span>), <span class="dt">lty=</span><span class="dv">1</span>, <span class="dt">cex=</span><span class="fl">0.8</span>,</a>
<a class="sourceLine" id="cb63-5" title="5">       <span class="dt">title=</span><span class="st">&quot;Treatment Group&quot;</span>, <span class="dt">text.font=</span><span class="dv">6</span>)</a></code></pre></div>
<p><img src="Rotterdam_files/figure-html/unnamed-chunk-47-1.png" width="672" /></p>
<p>As we have discussed in Chapter 2, we know that generally chemotherapy is used on patients with age lower than 50 years old and hormontherapy is used on patients with age higher than 50 years old. Based on the difference of treatment, we could see that chemotherapy has a better effect than hormontherapy with respect to death time and a smaller yet still better effect regarding the recurrence time.</p>
<p><code>Treatment</code> vs. <code>drecurtime</code></p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb64-1" title="1">KM_Treatment_drecur &lt;-<span class="st"> </span><span class="kw">survfit</span>(<span class="kw">Surv</span>(drecurtime, death) <span class="op">~</span><span class="st"> </span>Treatment, <span class="dt">data =</span> rotterdam_recur)</a>
<a class="sourceLine" id="cb64-2" title="2"><span class="kw">plot</span>(KM_Treatment_drecur, <span class="dt">conf.int =</span> <span class="ot">FALSE</span>, <span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;black&quot;</span>, <span class="st">&quot;red&quot;</span>, <span class="st">&quot;blue&quot;</span>, <span class="st">&quot;orange&quot;</span>), <span class="dt">xlab=</span><span class="st">&quot;Days&quot;</span>, <span class="dt">ylab=</span><span class="st">&quot;Survival&quot;</span>)</a>
<a class="sourceLine" id="cb64-3" title="3"><span class="kw">legend</span>(<span class="dv">3700</span>, <span class="dv">1</span>, <span class="dt">legend=</span><span class="kw">c</span>(<span class="st">&quot;Both&quot;</span>, <span class="st">&quot;Chemo&quot;</span>,<span class="st">&quot;Hormon&quot;</span>, <span class="st">&quot;NaN/Other Treatment&quot;</span>),</a>
<a class="sourceLine" id="cb64-4" title="4">       <span class="dt">col=</span><span class="kw">c</span>(<span class="st">&quot;black&quot;</span>, <span class="st">&quot;red&quot;</span>, <span class="st">&quot;blue&quot;</span>, <span class="st">&quot;orange&quot;</span>), <span class="dt">lty=</span><span class="dv">1</span>, <span class="dt">cex=</span><span class="fl">0.8</span>,</a>
<a class="sourceLine" id="cb64-5" title="5">       <span class="dt">title=</span><span class="st">&quot;Treatment Group&quot;</span>, <span class="dt">text.font=</span><span class="dv">6</span>)</a></code></pre></div>
<p><img src="Rotterdam_files/figure-html/unnamed-chunk-48-1.png" width="672" /></p>
<p>However, sadly enough, from the above plot we could see that no matter what treatment a patient use, it does not make a difference for the death survival time after cancer cells have recurred. This matches our conclusion from the visualization in Chapter 2.</p>
</div>
</div>
<div id="parametric-models" class="section level2">
<h2><span class="header-section-number">3.4</span> Parametric Models</h2>
<p>Another point that we are going to explore is if we would be able to fit our data to a parametric model. This matters since if we could fit any parametric model, then we should have a model good enough to generate predictions of breast cancer patients’ survival and would have nice and interpretable coefficients to work with.</p>
<p>To do so, we will begin by checking if any of Exponential, Weibull, or Log-normal distribution would be adequate parametric assumption to cast on our data. We will verify the adequacy by checking the Cox-Snell residual plot. We will be fitting models using variables: <code>Treatment</code>, <code>size</code>, <code>nodes</code>, <code>age</code>(We have shown in Chapter 2 that age is a confounder for categories in Treatment).</p>
<div id="user-defined-cox-snell-function" class="section level3">
<h3><span class="header-section-number">3.4.1</span> User-defined Cox-Snell function</h3>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb65-1" title="1"><span class="co"># The Cox-Snell function takes as inputs</span></a>
<a class="sourceLine" id="cb65-2" title="2"><span class="co"># 1. A vector of Cox-Snell residuals created by the user based on the model being evaluated,</span></a>
<a class="sourceLine" id="cb65-3" title="3"><span class="co"># 2. A status vector</span></a>
<a class="sourceLine" id="cb65-4" title="4"><span class="co"># 3. Optional x- and y- limits for the resulting plot</span></a>
<a class="sourceLine" id="cb65-5" title="5"></a>
<a class="sourceLine" id="cb65-6" title="6">CoxSnell =<span class="st"> </span><span class="cf">function</span>(cs,status,<span class="dt">xlim=</span><span class="ot">NULL</span>,<span class="dt">ylim=</span><span class="ot">NULL</span>)</a>
<a class="sourceLine" id="cb65-7" title="7">{</a>
<a class="sourceLine" id="cb65-8" title="8">kmcs =<span class="st"> </span><span class="kw">survfit</span>(<span class="kw">Surv</span>(<span class="kw">jitter</span>(cs,<span class="dt">amount=</span>(<span class="kw">max</span>(cs)<span class="op">-</span><span class="kw">min</span>(cs))<span class="op">/</span><span class="dv">1000</span>),status) <span class="op">~</span><span class="st"> </span><span class="dv">1</span>)<span class="op">$</span>surv</a>
<a class="sourceLine" id="cb65-9" title="9"></a>
<a class="sourceLine" id="cb65-10" title="10"><span class="kw">plot</span>(<span class="kw">log</span>(<span class="op">-</span><span class="kw">log</span>(kmcs)) <span class="op">~</span><span class="st"> </span><span class="kw">sort</span>(<span class="kw">log</span>(cs)) ,</a>
<a class="sourceLine" id="cb65-11" title="11">      <span class="dt">xlab=</span><span class="st">&quot;log(Cox-Snell)&quot;</span>, <span class="dt">ylab=</span><span class="st">&quot;log(-log(S(Cox-Snell)))&quot;</span>, <span class="dt">xlim=</span>xlim, <span class="dt">ylim=</span>ylim )</a>
<a class="sourceLine" id="cb65-12" title="12"></a>
<a class="sourceLine" id="cb65-13" title="13"><span class="kw">abline</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dt">col=</span><span class="st">&#39;red&#39;</span>)</a>
<a class="sourceLine" id="cb65-14" title="14">}</a></code></pre></div>
</div>
<div id="exponential-models" class="section level3">
<h3><span class="header-section-number">3.4.2</span> Exponential models</h3>
<p>We will begin by verifying the adequacy of Exponential model.</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb66-1" title="1">Dexp &lt;-<span class="st"> </span><span class="kw">survreg</span>(<span class="kw">Surv</span>(dtime, death) <span class="op">~</span><span class="st"> </span>Treatment <span class="op">+</span><span class="st"> </span>size <span class="op">+</span><span class="st"> </span>nodes <span class="op">+</span><span class="st"> </span>age, <span class="dt">dist=</span><span class="st">&#39;exponential&#39;</span>, <span class="dt">data=</span>rotterdam)</a>
<a class="sourceLine" id="cb66-2" title="2">Dexp</a></code></pre></div>
<pre><code>## Call:
## survreg(formula = Surv(dtime, death) ~ Treatment + size + nodes + 
##     age, data = rotterdam, dist = &quot;exponential&quot;)
## 
## Coefficients:
##                  (Intercept)               TreatmentChemo 
##                  10.49678202                  -0.51997169 
##              TreatmentHormon TreatmentNaN/Other Treatment 
##                  -0.44961578                  -0.46574886 
##                    size20-50                      size&gt;50 
##                  -0.46803053                  -0.81548193 
##                        nodes                          age 
##                  -0.06997150                  -0.01412165 
## 
## Scale fixed at 1 
## 
## Loglik(model)= -12137   Loglik(intercept only)= -12360.4
##  Chisq= 446.94 on 7 degrees of freedom, p= &lt;2e-16 
## n= 2982</code></pre>
<p><img src="Cox-Snell/DexpDeath.png" /></p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb68-1" title="1">Dexp &lt;-<span class="st"> </span><span class="kw">survreg</span>(<span class="kw">Surv</span>(rtime, recur) <span class="op">~</span><span class="st"> </span>Treatment <span class="op">+</span><span class="st"> </span>size <span class="op">+</span><span class="st"> </span>nodes <span class="op">+</span><span class="st"> </span>age, <span class="dt">dist=</span><span class="st">&#39;exponential&#39;</span>, <span class="dt">data=</span>rotterdam)</a>
<a class="sourceLine" id="cb68-2" title="2">Dexp</a></code></pre></div>
<pre><code>## Call:
## survreg(formula = Surv(rtime, recur) ~ Treatment + size + nodes + 
##     age, data = rotterdam, dist = &quot;exponential&quot;)
## 
## Coefficients:
##                  (Intercept)               TreatmentChemo 
##                  8.818707424                 -0.372797596 
##              TreatmentHormon TreatmentNaN/Other Treatment 
##                 -0.536512833                 -0.490056002 
##                    size20-50                      size&gt;50 
##                 -0.404626936                 -0.719554358 
##                        nodes                          age 
##                 -0.082728526                  0.008130282 
## 
## Scale fixed at 1 
## 
## Loglik(model)= -13917.5   Loglik(intercept only)= -14153.7
##  Chisq= 472.4 on 7 degrees of freedom, p= &lt;2e-16 
## n= 2982</code></pre>
<p><img src="Cox-Snell/DexpRecur.png" /></p>
<p>The Exponential does not seem adequate in this case.</p>
</div>
<div id="weibull-models" class="section level3">
<h3><span class="header-section-number">3.4.3</span> Weibull models</h3>
<p>Next we will examine the adequacy of Weibull model.</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb70-1" title="1">Dweibull &lt;-<span class="st"> </span><span class="kw">survreg</span>(<span class="kw">Surv</span>(dtime, death) <span class="op">~</span><span class="st"> </span>Treatment <span class="op">+</span><span class="st"> </span>size <span class="op">+</span><span class="st"> </span>nodes <span class="op">+</span><span class="st"> </span>age, <span class="dt">dist=</span><span class="st">&#39;weibull&#39;</span>, <span class="dt">data=</span>rotterdam)</a>
<a class="sourceLine" id="cb70-2" title="2">Dweibull</a></code></pre></div>
<pre><code>## Call:
## survreg(formula = Surv(dtime, death) ~ Treatment + size + nodes + 
##     age, data = rotterdam, dist = &quot;weibull&quot;)
## 
## Coefficients:
##                  (Intercept)               TreatmentChemo 
##                   9.93741760                  -0.40097983 
##              TreatmentHormon TreatmentNaN/Other Treatment 
##                  -0.40778590                  -0.36210464 
##                    size20-50                      size&gt;50 
##                  -0.35546640                  -0.65448317 
##                        nodes                          age 
##                  -0.05589248                  -0.01125732 
## 
## Scale= 0.739963 
## 
## Loglik(model)= -12068.9   Loglik(intercept only)= -12322.7
##  Chisq= 507.49 on 7 degrees of freedom, p= &lt;2e-16 
## n= 2982</code></pre>
<p><img src="Cox-Snell/DweibullDeath.png" /></p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb72-1" title="1">Dweibull &lt;-<span class="st"> </span><span class="kw">survreg</span>(<span class="kw">Surv</span>(rtime, recur) <span class="op">~</span><span class="st"> </span>Treatment <span class="op">+</span><span class="st"> </span>size <span class="op">+</span><span class="st"> </span>nodes <span class="op">+</span><span class="st"> </span>age, <span class="dt">dist=</span><span class="st">&#39;weibull&#39;</span>, <span class="dt">data=</span>rotterdam)</a>
<a class="sourceLine" id="cb72-2" title="2">Dweibull</a></code></pre></div>
<pre><code>## Call:
## survreg(formula = Surv(rtime, recur) ~ Treatment + size + nodes + 
##     age, data = rotterdam, dist = &quot;weibull&quot;)
## 
## Coefficients:
##                  (Intercept)               TreatmentChemo 
##                  8.830213089                 -0.376480833 
##              TreatmentHormon TreatmentNaN/Other Treatment 
##                 -0.539278367                 -0.495766112 
##                    size20-50                      size&gt;50 
##                 -0.410910817                 -0.727355688 
##                        nodes                          age 
##                 -0.083786844                  0.008292188 
## 
## Scale= 1.018498 
## 
## Loglik(model)= -13917.1   Loglik(intercept only)= -14145.7
##  Chisq= 457.19 on 7 degrees of freedom, p= &lt;2e-16 
## n= 2982</code></pre>
<p><img src="Cox-Snell/DweibullRecur.png" /></p>
<p>The Weibull model is still not adequate.</p>
</div>
<div id="log-normal-models" class="section level3">
<h3><span class="header-section-number">3.4.4</span> Log-normal models</h3>
<p>Finally, we will examine the adequacy of Log-normal model.</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb74-1" title="1">Dlnorm &lt;-<span class="st"> </span><span class="kw">survreg</span>(<span class="kw">Surv</span>(dtime, death) <span class="op">~</span><span class="st"> </span>Treatment <span class="op">+</span><span class="st"> </span>size <span class="op">+</span><span class="st"> </span>nodes <span class="op">+</span><span class="st"> </span>age , <span class="dt">dist=</span><span class="st">&#39;lognormal&#39;</span>, <span class="dt">data=</span>rotterdam)</a>
<a class="sourceLine" id="cb74-2" title="2">Dlnorm</a></code></pre></div>
<pre><code>## Call:
## survreg(formula = Surv(dtime, death) ~ Treatment + size + nodes + 
##     age, data = rotterdam, dist = &quot;lognormal&quot;)
## 
## Coefficients:
##                  (Intercept)               TreatmentChemo 
##                  9.709442268                 -0.431016329 
##              TreatmentHormon TreatmentNaN/Other Treatment 
##                 -0.346351742                 -0.423626557 
##                    size20-50                      size&gt;50 
##                 -0.372703559                 -0.654189313 
##                        nodes                          age 
##                 -0.079103425                 -0.009903862 
## 
## Scale= 1.077329 
## 
## Loglik(model)= -12034.1   Loglik(intercept only)= -12286.5
##  Chisq= 504.67 on 7 degrees of freedom, p= &lt;2e-16 
## n= 2982</code></pre>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb76-1" title="1">CS_LnormD &lt;-<span class="st"> </span><span class="op">-</span><span class="kw">log</span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="kw">plnorm</span>(rotterdam<span class="op">$</span>dtime, <span class="fl">9.709442268-0.431016329</span><span class="op">*</span>(rotterdam<span class="op">$</span>Treatment<span class="op">==</span><span class="st">&quot;Chemo&quot;</span>)</a>
<a class="sourceLine" id="cb76-2" title="2">                                                  <span class="fl">-0.346351742</span><span class="op">*</span>(rotterdam<span class="op">$</span>Treatment<span class="op">==</span><span class="st">&quot;Hormon&quot;</span>)  </a>
<a class="sourceLine" id="cb76-3" title="3">                                                  <span class="fl">-0.423626557</span><span class="op">*</span>(rotterdam<span class="op">$</span>Treatment<span class="op">==</span><span class="st">&quot;NaN/Other Treatment&quot;</span>)</a>
<a class="sourceLine" id="cb76-4" title="4">                                                  <span class="fl">-0.372703559</span><span class="op">*</span>(rotterdam<span class="op">$</span>size<span class="op">==</span><span class="st">&quot;20-50&quot;</span>)</a>
<a class="sourceLine" id="cb76-5" title="5">                                                  <span class="fl">-0.654189313</span><span class="op">*</span>(rotterdam<span class="op">$</span>size<span class="op">==</span><span class="st">&quot;&gt;50&quot;</span>)</a>
<a class="sourceLine" id="cb76-6" title="6">                                                  <span class="fl">-0.079103425</span><span class="op">*</span>rotterdam<span class="op">$</span>nodes </a>
<a class="sourceLine" id="cb76-7" title="7">                                                  <span class="fl">-0.009903862</span><span class="op">*</span>rotterdam<span class="op">$</span>age, </a>
<a class="sourceLine" id="cb76-8" title="8">                                       <span class="fl">1.077329</span>))</a>
<a class="sourceLine" id="cb76-9" title="9"><span class="co"># Make appropriate graph using CoxSnell function</span></a>
<a class="sourceLine" id="cb76-10" title="10"><span class="kw">CoxSnell</span>(CS_LnormD, rotterdam<span class="op">$</span>death)</a></code></pre></div>
<p><img src="Rotterdam_files/figure-html/unnamed-chunk-54-1.png" width="672" /></p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb77-1" title="1">Rlnorm &lt;-<span class="st"> </span><span class="kw">survreg</span>(<span class="kw">Surv</span>(rtime, recur) <span class="op">~</span><span class="st"> </span>Treatment <span class="op">+</span><span class="st"> </span>size <span class="op">+</span><span class="st"> </span>nodes <span class="op">+</span><span class="st"> </span>age, <span class="dt">dist=</span><span class="st">&#39;lognormal&#39;</span>, <span class="dt">data=</span>rotterdam)</a>
<a class="sourceLine" id="cb77-2" title="2">Rlnorm</a></code></pre></div>
<pre><code>## Call:
## survreg(formula = Surv(rtime, recur) ~ Treatment + size + nodes + 
##     age, data = rotterdam, dist = &quot;lognormal&quot;)
## 
## Coefficients:
##                  (Intercept)               TreatmentChemo 
##                  8.514204484                 -0.382172447 
##              TreatmentHormon TreatmentNaN/Other Treatment 
##                 -0.479063703                 -0.605193863 
##                    size20-50                      size&gt;50 
##                 -0.458345796                 -0.738657689 
##                        nodes                          age 
##                 -0.107708963                  0.009059467 
## 
## Scale= 1.340545 
## 
## Loglik(model)= -13803.8   Loglik(intercept only)= -14045.8
##  Chisq= 483.94 on 7 degrees of freedom, p= &lt;2e-16 
## n= 2982</code></pre>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb79-1" title="1">CS_LnormR &lt;-<span class="st"> </span><span class="op">-</span><span class="kw">log</span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="kw">plnorm</span>(rotterdam<span class="op">$</span>rtime, <span class="fl">8.514204484-0.382172447</span><span class="op">*</span>(rotterdam<span class="op">$</span>Treatment<span class="op">==</span><span class="st">&quot;Chemo&quot;</span>)</a>
<a class="sourceLine" id="cb79-2" title="2">                                                  <span class="fl">-0.479063703</span><span class="op">*</span>(rotterdam<span class="op">$</span>Treatment<span class="op">==</span><span class="st">&quot;Hormon&quot;</span>)   </a>
<a class="sourceLine" id="cb79-3" title="3">                                                  <span class="fl">-0.605193863</span><span class="op">*</span>(rotterdam<span class="op">$</span>Treatment<span class="op">==</span><span class="st">&quot;NaN/Other Treatment&quot;</span>)</a>
<a class="sourceLine" id="cb79-4" title="4">                                                  <span class="fl">-0.458345796</span><span class="op">*</span>(rotterdam<span class="op">$</span>size<span class="op">==</span><span class="st">&quot;20-50&quot;</span>)</a>
<a class="sourceLine" id="cb79-5" title="5">                                                  <span class="fl">-0.738657689</span><span class="op">*</span>(rotterdam<span class="op">$</span>size<span class="op">==</span><span class="st">&quot;&gt;50&quot;</span>)</a>
<a class="sourceLine" id="cb79-6" title="6">                                                  <span class="fl">-0.107708963</span><span class="op">*</span>rotterdam<span class="op">$</span>nodes </a>
<a class="sourceLine" id="cb79-7" title="7">                                                  <span class="fl">+0.009059467</span><span class="op">*</span>rotterdam<span class="op">$</span>age, </a>
<a class="sourceLine" id="cb79-8" title="8">                                       <span class="fl">1.340545</span>))</a>
<a class="sourceLine" id="cb79-9" title="9"></a>
<a class="sourceLine" id="cb79-10" title="10"><span class="co"># Make appropriate graph using CoxSnell function</span></a>
<a class="sourceLine" id="cb79-11" title="11"><span class="kw">CoxSnell</span>(CS_LnormR, rotterdam<span class="op">$</span>recur)</a></code></pre></div>
<p><img src="Rotterdam_files/figure-html/unnamed-chunk-55-1.png" width="672" /></p>
<p>We could see that the Log-normal parametric model is an adequate model for both the <code>dtime</code> and <code>rtime</code> vs. <code>Treatment</code> + <code>size</code> + <code>nodes</code> + <code>age</code>.</p>
<p>As to why the Log-normal model would be suitable for the data, we are not sure. One thing to consider is that the non-monotonic implication of the data casted by the log-normal model.</p>
</div>
<div id="positive-coefficient-of-age" class="section level3">
<h3><span class="header-section-number">3.4.5</span> Positive coefficient of <code>age</code></h3>
<p>In the <code>rtime ~ Treatment + size + nodes + age</code> models, it is surprised to see that the coefficient of <code>age</code> is positive, though the value is small. One possible explanation could be the idea of “competing events” and “competing risk”.</p>
<p>In this scenario, having recurred breast cancer and being dead could be somewhat “competing events”. Though they are not completely “cannot happen on one person at the same time”, it is still reasonable to think that for older patients, it is more likely to die from breast cancer or other complications than being cancer-free for years and then having breast cancer recurred; whereas for younger people, the risk of having recurrent breast cancer could be higher than being dead from the first breast cancer.</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb80-1" title="1">rotterdam_new &lt;-<span class="st"> </span>rotterdam <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb80-2" title="2"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">state =</span> <span class="kw">ifelse</span>(death <span class="op">==</span><span class="st"> </span><span class="dv">1</span> <span class="op">&amp;</span><span class="st"> </span>recur <span class="op">==</span><span class="st"> </span><span class="dv">0</span>, <span class="st">&quot;death&quot;</span>,</a>
<a class="sourceLine" id="cb80-3" title="3">                 <span class="kw">ifelse</span>(death <span class="op">==</span><span class="st"> </span><span class="dv">0</span> <span class="op">&amp;</span><span class="st"> </span>recur <span class="op">==</span><span class="st"> </span><span class="dv">1</span>, <span class="st">&quot;recur&quot;</span>, </a>
<a class="sourceLine" id="cb80-4" title="4">                 <span class="kw">ifelse</span>(death <span class="op">==</span><span class="st"> </span><span class="dv">1</span> <span class="op">&amp;</span><span class="st"> </span>recur <span class="op">==</span><span class="st"> </span><span class="dv">1</span>, <span class="st">&quot;both&quot;</span>, <span class="st">&quot;neither&quot;</span>))))</a>
<a class="sourceLine" id="cb80-5" title="5"></a>
<a class="sourceLine" id="cb80-6" title="6"><span class="kw">ggplot</span>(rotterdam_new, <span class="kw">aes</span>(<span class="dt">x=</span>age, <span class="dt">color=</span>state, <span class="dt">fill=</span>state)) <span class="op">+</span></a>
<a class="sourceLine" id="cb80-7" title="7"><span class="st">  </span><span class="kw">geom_density</span>(<span class="dt">alpha=</span><span class="fl">0.3</span>)</a></code></pre></div>
<p><img src="Rotterdam_files/figure-html/unnamed-chunk-56-1.png" width="672" /></p>
<p>The plot above also helps verifying the idea. We can find that the group who has been dead during the study but has never had breast cancer recurred (the green one) tends to be older than others.</p>
<p>The positive coefficient of <code>age</code> in the log-normal model may seem indicating a protective effect of being old against having breast cancer recurred, but this should not be the true case. It is very likely that this is caused by the competing risk between being dead and having breast cancer recurred for people in different age group. The elderly patients are less likely to suffer from recurrent breast cancer because they are more likely to die from breast cancer or other complications during the treatment after the first diagnosis.</p>
</div>
</div>
<div id="cox-ph-model" class="section level2">
<h2><span class="header-section-number">3.5</span> Cox-PH model:</h2>
<p>Another very important part of a survival analysis is building and interpreting the coxph model. With this model, once we have proof of the validation of the PH assumption of the model, we could have nice coefficients to interpret as the logarithm of HR(hazard ratio) among different groups. We will be following the way that we built our parametric models, by using Survival times vs. <code>age</code> + <code>size</code> + <code>nodes</code> + <code>Treatment</code>.</p>
<div id="dtime-coxph-model" class="section level3">
<h3><span class="header-section-number">3.5.1</span> <code>dtime</code> coxph model</h3>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb81-1" title="1">m_death_withage =<span class="st"> </span><span class="kw">coxph</span>(<span class="kw">Surv</span>(dtime, death) <span class="op">~</span><span class="st"> </span>Treatment <span class="op">+</span><span class="st"> </span>size <span class="op">+</span><span class="st"> </span>nodes <span class="op">+</span><span class="st"> </span>age, <span class="dt">data=</span>rotterdam)</a>
<a class="sourceLine" id="cb81-2" title="2">m_death_withage</a></code></pre></div>
<pre><code>## Call:
## coxph(formula = Surv(dtime, death) ~ Treatment + size + nodes + 
##     age, data = rotterdam)
## 
##                                  coef exp(coef) se(coef)      z        p
## TreatmentChemo               0.546830  1.727768 0.360076  1.519    0.129
## TreatmentHormon              0.519838  1.681756 0.366212  1.420    0.156
## TreatmentNaN/Other Treatment 0.496324  1.642672 0.356927  1.391    0.164
## size20-50                    0.477235  1.611612 0.065146  7.326 2.38e-13
## size&gt;50                      0.865167  2.375402 0.090893  9.519  &lt; 2e-16
## nodes                        0.074146  1.076964 0.004864 15.244  &lt; 2e-16
## age                          0.014904  1.015016 0.002562  5.818 5.94e-09
## 
## Likelihood ratio test=487.1  on 7 df, p=&lt; 2.2e-16
## n= 2982, number of events= 1272</code></pre>
<p>First we should check if the PH assumption holds. We will be using a formal test.</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb83-1" title="1"><span class="kw">cox.zph</span>(m_death_withage)</a></code></pre></div>
<pre><code>##           chisq df       p
## Treatment  4.45  3 0.21657
## size       4.81  2 0.09023
## nodes      3.32  1 0.06850
## age       15.12  1 0.00010
## GLOBAL    25.38  7 0.00065</code></pre>
<p>One of the variable, <code>age</code>, has p-value smaller than 0.05, which indicates the violation of the PH assumption. So we can not intepret the coefficients right away.</p>
<p>One way we came up to solve this problem is to put stratification on <code>age</code> by putting a <code>strata()</code> on <code>age</code> when fitting the model. What this does is to recognize the correlation between <code>age</code> and the <code>dtime</code>, but not actually including it in our model results.</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb85-1" title="1">m_death_strataage =<span class="st"> </span><span class="kw">coxph</span>(<span class="kw">Surv</span>(dtime, death) <span class="op">~</span><span class="st"> </span>Treatment <span class="op">+</span><span class="st"> </span>size <span class="op">+</span><span class="st"> </span>nodes <span class="op">+</span><span class="st"> </span><span class="kw">strata</span>(age), <span class="dt">data=</span>rotterdam)</a>
<a class="sourceLine" id="cb85-2" title="2">m_death_strataage</a></code></pre></div>
<pre><code>## Call:
## coxph(formula = Surv(dtime, death) ~ Treatment + size + nodes + 
##     strata(age), data = rotterdam)
## 
##                                  coef exp(coef) se(coef)      z        p
## TreatmentChemo               0.566734  1.762501 0.368984  1.536    0.125
## TreatmentHormon              0.571493  1.770909 0.375700  1.521    0.128
## TreatmentNaN/Other Treatment 0.497674  1.644890 0.365574  1.361    0.173
## size20-50                    0.464177  1.590704 0.066890  6.939 3.94e-12
## size&gt;50                      0.772204  2.164532 0.097352  7.932 2.16e-15
## nodes                        0.078158  1.081294 0.005365 14.567  &lt; 2e-16
## 
## Likelihood ratio test=391.7  on 6 df, p=&lt; 2.2e-16
## n= 2982, number of events= 1272</code></pre>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb87-1" title="1"><span class="kw">cox.zph</span>(m_death_strataage)</a></code></pre></div>
<pre><code>##           chisq df    p
## Treatment  3.60  3 0.31
## size       4.32  2 0.12
## nodes      1.37  1 0.24
## GLOBAL     9.64  6 0.14</code></pre>
<p>Now we can see that all the variables’ p-value are greater than 0.05 which indicates the PH assumption holds in our model. Now we can finally intepret the coefficients.</p>
<p>For treatments, we can see that Chemotherapy, Hormontherapy and Other Treatment all have higher risks than patients receiving both therapies. However, note that all three p-values are greater than 0.05, which means that we do not have significant evidence for such relationships. We think that this is because there are too few data point receiving both therapies.</p>
<p>Now let’s look at tumor size. It is clear that patients with larger tumor size enjoy higher risks, and as the size grows, the risk is also increasing. such relationship is significant as we can see from the p-values since they are all less than 0.05.</p>
<p>For lymph nodes tested positive, we could see that for 1 unit increase in the number of nodes, the risk will increase by a multiplicative of 1.08. This relationship is also significant as the p-value is smaller than 0.05.</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb89-1" title="1">m_recur =<span class="st"> </span><span class="kw">coxph</span>(<span class="kw">Surv</span>(rtime, recur) <span class="op">~</span><span class="st"> </span>Treatment <span class="op">+</span><span class="st"> </span>size <span class="op">+</span><span class="st"> </span>nodes <span class="op">+</span><span class="st"> </span>age, <span class="dt">data=</span>rotterdam)</a>
<a class="sourceLine" id="cb89-2" title="2">m_recur</a></code></pre></div>
<pre><code>## Call:
## coxph(formula = Surv(rtime, recur) ~ Treatment + size + nodes + 
##     age, data = rotterdam)
## 
##                                   coef exp(coef)  se(coef)      z        p
## TreatmentChemo                0.324447  1.383266  0.283541  1.144 0.252512
## TreatmentHormon               0.436864  1.547846  0.290953  1.501 0.133227
## TreatmentNaN/Other Treatment  0.459422  1.583159  0.280366  1.639 0.101286
## size20-50                     0.399867  1.491626  0.057857  6.911 4.80e-12
## size&gt;50                       0.684610  1.982999  0.087589  7.816 5.44e-15
## nodes                         0.080239  1.083546  0.004575 17.539  &lt; 2e-16
## age                          -0.008653  0.991385  0.002314 -3.739 0.000184
## 
## Likelihood ratio test=429.7  on 7 df, p=&lt; 2.2e-16
## n= 2982, number of events= 1518</code></pre>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb91-1" title="1"><span class="kw">cox.zph</span>(m_recur)</a></code></pre></div>
<pre><code>##            chisq df       p
## Treatment  7.943  3   0.047
## size      26.427  2 1.8e-06
## nodes      5.297  1   0.021
## age        0.104  1   0.747
## GLOBAL    42.374  7 4.4e-07</code></pre>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb93-1" title="1">m_recur =<span class="st"> </span><span class="kw">coxph</span>(<span class="kw">Surv</span>(rtime, recur) <span class="op">~</span><span class="st"> </span><span class="kw">strata</span>(Treatment) <span class="op">+</span><span class="st"> </span>size <span class="op">+</span><span class="st"> </span>nodes <span class="op">+</span><span class="st"> </span>age, <span class="dt">data=</span>rotterdam)</a>
<a class="sourceLine" id="cb93-2" title="2">m_recur</a></code></pre></div>
<pre><code>## Call:
## coxph(formula = Surv(rtime, recur) ~ strata(Treatment) + size + 
##     nodes + age, data = rotterdam)
## 
##                coef exp(coef)  se(coef)      z        p
## size20-50  0.396037  1.485924  0.057899  6.840 7.91e-12
## size&gt;50    0.693201  2.000107  0.087565  7.916 2.44e-15
## nodes      0.080220  1.083525  0.004576 17.529  &lt; 2e-16
## age       -0.008805  0.991233  0.002315 -3.804 0.000142
## 
## Likelihood ratio test=404.3  on 4 df, p=&lt; 2.2e-16
## n= 2982, number of events= 1518</code></pre>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb95-1" title="1"><span class="kw">cox.zph</span>(m_recur)</a></code></pre></div>
<pre><code>##          chisq df       p
## size   31.3790  2 1.5e-07
## nodes   9.8790  1  0.0017
## age     0.0979  1  0.7544
## GLOBAL 35.2423  4 4.1e-07</code></pre>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="data-exploration.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="conclusion.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Rotterdam.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
